// Günün Bilgisi — "Bunu biliyor muydun?" havuzu
// Her gün tarihe göre deterministik olarak bir bilgi seçilir.
// KPSS/AGS genel kültür odaklı, kısa ve ilgi çekici bilgiler.

export interface DailyFact {
  id: string;
  category: 'tarih' | 'cografya' | 'vatandaslik' | 'genel';
  text: string;
}

export const DAILY_FACTS: DailyFact[] = [
  { id: 'f01', category: 'cografya', text: 'Türkiye’nin en uzun nehri Kızılırmak’tır (1.355 km) ve tamamı Türkiye sınırları içinde akar.' },
  { id: 'f02', category: 'cografya', text: 'Türkiye’nin en yüksek dağı 5.137 m ile Ağrı Dağı’dır. Van Gölü ise en büyük gölümüzdür.' },
  { id: 'f03', category: 'tarih', text: 'Türkiye Büyük Millet Meclisi 23 Nisan 1920’de açıldı. Bu tarih aynı zamanda Ulusal Egemenlik ve Çocuk Bayramı’dır.' },
  { id: 'f04', category: 'tarih', text: 'Cumhuriyet 29 Ekim 1923’te ilan edildi ve ilk Cumhurbaşkanı Mustafa Kemal Atatürk oldu.' },
  { id: 'f05', category: 'vatandaslik', text: 'Türkiye’de yasama yetkisi TBMM’ye, yürütme Cumhurbaşkanına, yargı ise bağımsız mahkemelere aittir.' },
  { id: 'f06', category: 'tarih', text: 'Lozan Antlaşması 24 Temmuz 1923’te imzalandı ve yeni Türkiye Devleti’nin sınırları büyük ölçüde bu antlaşmayla belirlendi.' },
  { id: 'f07', category: 'genel', text: 'Türkçe, Latin alfabesine 1 Kasım 1928’de Harf İnkılabı ile geçti.' },
  { id: 'f08', category: 'cografya', text: 'Türkiye üç tarafı denizlerle çevrilidir: kuzeyde Karadeniz, batıda Ege, güneyde Akdeniz.' },
  { id: 'f09', category: 'tarih', text: 'İstanbul (Konstantinopolis) 29 Mayıs 1453’te Fatih Sultan Mehmet tarafından fethedildi.' },
  { id: 'f10', category: 'vatandaslik', text: '1982 Anayasası, Türkiye’nin yürürlükteki anayasasıdır ve 7 Kasım 1982’de halk oylamasıyla kabul edilmiştir.' },
  { id: 'f11', category: 'tarih', text: 'Kadınlara seçme ve seçilme hakkı Türkiye’de 1934’te tanındı; bu, birçok Avrupa ülkesinden daha önceydi.' },
  { id: 'f12', category: 'cografya', text: 'Türkiye’nin en kalabalık şehri İstanbul’dur ve tek şehir olarak iki kıtada yer alır: Avrupa ve Asya.' },
  { id: 'f13', category: 'genel', text: 'Anıtkabir’in mimarları Emin Onat ve Orhan Arda’dır; 1953’te tamamlanmıştır.' },
  { id: 'f14', category: 'tarih', text: 'Sakarya Meydan Muharebesi (1921) “Subay Savaşı” olarak da anılır ve Batı Cephesi’nde dönüm noktasıdır.' },
  { id: 'f15', category: 'cografya', text: 'Tuz Gölü, Türkiye’nin tuz ihtiyacının büyük bölümünü karşılar ve ikinci büyük gölüdür.' },
  { id: 'f16', category: 'vatandaslik', text: 'Anayasa Mahkemesi, kanunların anayasaya uygunluğunu denetleyen en yüksek yargı organlarından biridir.' },
  { id: 'f17', category: 'genel', text: 'Nasreddin Hoca’nın yaşadığı Akşehir, Konya’ya bağlıdır ve her yıl adına şenlikler düzenlenir.' },
  { id: 'f18', category: 'tarih', text: 'Osmanlı Devleti’ni Osman Bey 1299’da kurdu; devlet yaklaşık 600 yıl varlığını sürdürdü.' },
  { id: 'f19', category: 'cografya', text: 'Türkiye’nin en büyük yüzölçümüne sahip ili Konya’dır.' },
  { id: 'f20', category: 'genel', text: 'Türkiye’de zorunlu eğitim 12 yıldır ve “4+4+4” sistemi olarak bilinir.' },
  { id: 'f21', category: 'tarih', text: 'Çanakkale Deniz Zaferi 18 Mart 1915’te kazanıldı ve “Çanakkale geçilmez” sözü tarihe geçti.' },
  { id: 'f22', category: 'vatandaslik', text: 'Milletvekili genel seçimleri Türkiye’de 5 yılda bir yapılır.' },
  { id: 'f23', category: 'cografya', text: 'GAP (Güneydoğu Anadolu Projesi) Türkiye’nin en büyük bölgesel kalkınma projesidir; Fırat ve Dicle üzerinde kuruludur.' },
  { id: 'f24', category: 'genel', text: 'Türk Lirası simgesi (₺) 2012’de kabul edildi; tasarımı bir yarışmayla belirlendi.' },
  { id: 'f25', category: 'tarih', text: 'Malazgirt Savaşı 1071’de kazanıldı ve Anadolu’nun kapıları Türklere açıldı.' },
  { id: 'f26', category: 'cografya', text: 'Karadeniz Bölgesi, Türkiye’de en çok yağış alan bölgedir; bu yüzden ormanlar en geniş buradadır.' },
  { id: 'f27', category: 'genel', text: 'Kapadokya’daki peribacaları volkanik tüflerin binlerce yıllık erozyonuyla oluşmuştur.' },
  { id: 'f28', category: 'vatandaslik', text: 'Türkiye’de seçme yaşı 18’dir; ilk kez 1987’de referandumla düşürülmüştür.' },
  { id: 'f29', category: 'tarih', text: 'Mustafa Kemal’e “Atatürk” soyadı 24 Kasım 1934’te TBMM tarafından verildi.' },
  { id: 'f30', category: 'cografya', text: 'Pamukkale’nin bembeyaz travertenleri kalsiyum karbonat bakımından zengin sıcak sulardan oluşur.' },
  { id: 'f31', category: 'genel', text: 'Efes Antik Kenti İzmir’dedir ve dünyanın en iyi korunmuş antik kentlerinden biridir.' },
  { id: 'f32', category: 'tarih', text: 'Türkiye Cumhuriyeti’nin ilk başkenti Ankara’dır; 13 Ekim 1923’te başkent ilan edildi.' },
  { id: 'f33', category: 'vatandaslik', text: 'Hâkimler ve Savcılar Kurulu (HSK), yargı mensuplarının özlük işlerinden sorumludur.' },
  { id: 'f34', category: 'cografya', text: 'Türkiye’nin en derin gölü Van Gölü’dür ve suyu sodalı olduğu için “inci kefali” dışında çok az balık yaşar.' },
  { id: 'f35', category: 'genel', text: 'Göbeklitepe (Şanlıurfa) yaklaşık 12.000 yıl öncesine tarihlenir ve dünyanın bilinen en eski tapınağı sayılır.' },
  { id: 'f36', category: 'tarih', text: 'Kurtuluş Savaşı’nın son büyük zaferi Büyük Taarruz’dur (26 Ağustos 1922).' },
  { id: 'f37', category: 'cografya', text: 'Türkiye 7 coğrafi bölgeye ayrılır; en küçük yüzölçümüne sahip bölge Marmara’dır.' },
  { id: 'f38', category: 'genel', text: 'Türk kahvesi, 2013’te UNESCO İnsanlığın Somut Olmayan Kültürel Mirası listesine alındı.' },
  { id: 'f39', category: 'vatandaslik', text: 'Temel hak ve özgürlükler 1982 Anayasası’nın “Kişinin Hakları ve Ödevleri” bölümünde düzenlenir.' },
  { id: 'f40', category: 'tarih', text: 'İzmir 9 Eylül 1922’de düşman işgalinden kurtarıldı; bu tarih İzmir’in kurtuluşu olarak kutlanır.' },
  { id: 'f41', category: 'cografya', text: 'Fırat, Türkiye’nin en uzun akarsuyudur ama bir kısmı ülke dışında aktığı için “tamamı yurt içinde” olan en uzun nehir Kızılırmak’tır.' },
  { id: 'f42', category: 'genel', text: 'Mevlana Celaleddin Rumi’nin türbesi Konya’dadır ve her yıl Şeb-i Arus törenleriyle anılır.' },
  { id: 'f43', category: 'tarih', text: 'Malazgirt Zaferi (26 Ağustos 1071) ile Anadolu’nun kapıları Türklere açıldı; Alp Arslan’ın ordusu Bizans İmparatoru’nu esir aldı.' },
  { id: 'f44', category: 'tarih', text: 'Orhun Yazıtları, Türk adının geçtiği ilk yazılı belgelerdir ve bugünkü Moğolistan sınırları içindedir.' },
  { id: 'f45', category: 'tarih', text: 'İlk Türk matbaası 1727’de İbrahim Müteferrika tarafından kuruldu; ilk basılan eser bir sözlük olan Vankulu Lügati’dir.' },
  { id: 'f46', category: 'tarih', text: 'Yeniçeri Ocağı 1826’da II. Mahmut tarafından kaldırıldı; bu olay tarihe “Vaka-i Hayriye” (Hayırlı Olay) olarak geçti.' },
  { id: 'f47', category: 'tarih', text: 'Kurtuluş Savaşı’nın ilk kurşunu, 15 Mayıs 1919’da İzmir’in işgali sırasında gazeteci Hasan Tahsin tarafından atıldığı kabul edilir.' },
  { id: 'f48', category: 'tarih', text: 'Mustafa Kemal’e “Gazi” unvanı ve mareşallik rütbesi, Sakarya Zaferi’nden sonra 19 Eylül 1921’de TBMM tarafından verildi.' },
  { id: 'f49', category: 'tarih', text: 'Halifelik 3 Mart 1924’te kaldırıldı; aynı gün Tevhid-i Tedrisat Kanunu ile tüm okullar Milli Eğitim’e bağlandı.' },
  { id: 'f50', category: 'tarih', text: 'Türkiye’de soyadı kullanımı 1934’teki Soyadı Kanunu ile zorunlu oldu; TBMM, Mustafa Kemal’e “Atatürk” soyadını verdi.' },
  { id: 'f51', category: 'tarih', text: 'Osmanlı’nın en uzun süre tahtta kalan padişahı 46 yıllık saltanatıyla Kanuni Sultan Süleyman’dır.' },
  { id: 'f52', category: 'tarih', text: 'İstanbul’un fethinde kullanılan dev toplar, Macar usta Urban ile Türk dökümcüler tarafından Edirne’de döküldü.' },
  { id: 'f53', category: 'tarih', text: 'Türkiye, Kore Savaşı’na asker göndermesinin ardından 1952’de NATO’ya üye oldu.' },
  { id: 'f54', category: 'tarih', text: 'Kadınlar Türkiye’de milletvekili seçme-seçilme hakkını Fransa’dan 10, İtalya’dan 11 yıl önce kazandı (1934).' },
  { id: 'f55', category: 'tarih', text: 'Çanakkale Savaşı’nda (1915) tek gecede boğazdan geçmeye çalışan müttefik donanması, Nusret mayın gemisinin döşediği mayınlarla durduruldu.' },
  { id: 'f56', category: 'cografya', text: 'Van Gölü dünyanın en büyük sodalı gölüdür; suyu o kadar alkalidir ki çamaşır bile yıkanabilir.' },
  { id: 'f57', category: 'cografya', text: 'Türkiye, dünya bor rezervlerinin yaklaşık %70’ine sahiptir; bor cam, seramik ve uzay teknolojilerinde kullanılır.' },
  { id: 'f58', category: 'cografya', text: 'Dünya fındık üretiminin yaklaşık üçte ikisi Türkiye’den, özellikle Ordu ve Giresun’dan gelir.' },
  { id: 'f59', category: 'cografya', text: 'Türkiye’nin en kurak yeri Tuz Gölü çevresi (yılda ~250 mm yağış), en yağışlı yeri ise Rize’dir (2.200 mm üzeri).' },
  { id: 'f60', category: 'cografya', text: 'Kapadokya’daki peri bacaları, Erciyes ve Hasandağı’nın püskürttüğü volkanik tüflerin milyonlarca yıl aşınmasıyla oluştu.' },
  { id: 'f61', category: 'cografya', text: 'Pamukkale travertenleri, kalsiyum karbonat içeren sıcak suların çökelmesiyle oluşmuştur ve UNESCO Dünya Mirası’dır.' },
  { id: 'f62', category: 'cografya', text: '1915 Çanakkale Köprüsü, 2.023 metrelik orta açıklığıyla dünyanın en uzun orta açıklıklı asma köprüsüdür.' },
  { id: 'f63', category: 'cografya', text: 'Türkiye’nin en derin gölü 451 metreyle Van Gölü’dür; Hazar Gölü (Elazığ) ise tektonik kökenlidir.' },
  { id: 'f64', category: 'cografya', text: 'İstanbul Boğazı’nın en dar yeri yaklaşık 700 metredir (Anadolu Hisarı–Rumeli Hisarı arası).' },
  { id: 'f65', category: 'cografya', text: 'Türkiye’de 21 Haziran en uzun gündüz, 21 Aralık en uzun gecedir; Ekvator’da ise gece-gündüz hep eşittir.' },
  { id: 'f66', category: 'cografya', text: 'Nemrut Dağı’ndaki (Adıyaman) dev heykeller, Kommagene Kralı I. Antiochos’un anıt mezarına aittir ve UNESCO listesindedir.' },
  { id: 'f67', category: 'cografya', text: 'Türkiye’nin en uzun kara sınırı Suriye’yledir (911 km); en kısası ise sadece 18 km ile Nahçıvan (Azerbaycan) sınırıdır.' },
  { id: 'f68', category: 'cografya', text: 'Dünyanın en derin noktası Pasifik’teki Mariana Çukuru’dur (~11.000 m) — Everest bile içine sığar.' },
  { id: 'f69', category: 'cografya', text: 'Türkiye’de heyelanların çoğu, bol yağış ve eğimli arazi nedeniyle Karadeniz Bölgesi’nde ve ilkbaharda görülür.' },
  { id: 'f70', category: 'vatandaslik', text: 'TBMM 600 milletvekilinden oluşur; milletvekili seçilme yaşı 2017’de 25’ten 18’e indirildi.' },
  { id: 'f71', category: 'vatandaslik', text: 'Anayasa’nın ilk üç maddesi değiştirilemez; değiştirilmesi teklif dahi edilemez.' },
  { id: 'f72', category: 'vatandaslik', text: 'Bir kişi en fazla iki kez Cumhurbaşkanı seçilebilir; seçilebilmek için 40 yaş ve yükseköğrenim şartı aranır.' },
  { id: 'f73', category: 'vatandaslik', text: 'Türkiye’de seçimlerin yönetim ve denetimini Yüksek Seçim Kurulu (YSK) yürütür; kararları kesindir.' },
  { id: 'f74', category: 'vatandaslik', text: 'Vergi ödevi Anayasa’da düzenlenmiştir: herkes mali gücüne göre vergi vermekle yükümlüdür.' },
  { id: 'f75', category: 'vatandaslik', text: 'Kamu Denetçiliği Kurumu (Ombudsmanlık), vatandaşın idareyle yaşadığı sorunlarda ücretsiz başvurabileceği bir denetim yoludur.' },
  { id: 'f76', category: 'vatandaslik', text: '2010’dan beri hak ihlaline uğradığını düşünen herkes Anayasa Mahkemesi’ne bireysel başvuru yapabilir.' },
  { id: 'f77', category: 'vatandaslik', text: 'Türk tarihinin ilk anayasası 1876 Kanun-i Esasi, yeni Türk devletinin ilk anayasası ise 1921 Teşkilat-ı Esasiye’dir.' },
  { id: 'f78', category: 'vatandaslik', text: 'Muhtarlık, Türkiye’de siyasi partilerin aday gösteremediği tek seçimdir.' },
  { id: 'f79', category: 'vatandaslik', text: 'Yaşama hakkı en temel haktır; savaş ve olağanüstü hâlde bile bu hakkın özüne dokunulamaz.' },
  { id: 'f80', category: 'vatandaslik', text: 'Vali atamayla, belediye başkanı ise seçimle göreve gelir — biri merkezi yönetimi, diğeri yerel yönetimi temsil eder.' },
  { id: 'f81', category: 'genel', text: 'Aziz Sancar, DNA onarımı üzerine çalışmalarıyla 2015 Nobel Kimya Ödülü’nü kazanan ilk Türk bilim insanıdır.' },
  { id: 'f82', category: 'genel', text: 'Orhan Pamuk, 2006 Nobel Edebiyat Ödülü’nü kazanarak bu ödülü alan ilk Türk oldu.' },
  { id: 'f83', category: 'genel', text: 'Alper Gezeravcı, Ocak 2024’te Uluslararası Uzay İstasyonu’na giderek uzaya çıkan ilk Türk oldu.' },
  { id: 'f84', category: 'genel', text: 'Göbeklitepe (Şanlıurfa), Mısır piramitlerinden ~7.000 yıl daha eskidir ve bilinen en eski tapınak kompleksidir.' },
  { id: 'f85', category: 'genel', text: 'Truva Atı efsanesinin geçtiği antik Truva kenti, Çanakkale sınırları içindedir ve UNESCO Dünya Mirası’dır.' },
  { id: 'f86', category: 'genel', text: 'Dünyanın yedi harikasından ikisi Türkiye’deydi: Efes’teki Artemis Tapınağı ve Bodrum’daki Mausoleum.' },
  { id: 'f87', category: 'genel', text: 'İstiklal Marşı’nın şairi Mehmet Akif Ersoy, kazandığı para ödülünü almayı reddetmiştir.' },
  { id: 'f88', category: 'genel', text: 'Türkiye’nin ilk yerli otomobili 1961’de üretilen Devrim’dir; seri üretime geçen ilk yerli elektrikli marka ise TOGG’dur.' },
  { id: 'f89', category: 'genel', text: 'Kızılay, 1868’de “Osmanlı Yaralı ve Hasta Askerlere Yardım Cemiyeti” adıyla kuruldu.' },
  { id: 'f90', category: 'genel', text: 'Piri Reis’in 1513 tarihli dünya haritası, Amerika kıyılarını gösteren en eski haritalardan biridir.' },
  { id: 'f91', category: 'genel', text: 'Evliya Çelebi, 17. yüzyılda 50 yılda üç kıtayı gezdi ve gözlemlerini 10 ciltlik Seyahatname’de topladı.' },
  { id: 'f92', category: 'genel', text: 'Mimar Sinan, “ustalık eserim” dediği Selimiye Camii’ni 80’li yaşlarında tamamladı; cami UNESCO Dünya Mirası’dır.' },
  { id: 'f93', category: 'genel', text: 'İlk Türk kadın pilot Sabiha Gökçen, aynı zamanda dünyanın ilk kadın savaş pilotudur.' },
  { id: 'f94', category: 'genel', text: 'Katip Çelebi’nin “Cihannüma”sı, Osmanlı’nın en önemli coğrafya eseridir ve Avrupa dillerine çevrilmiştir.' },
  { id: 'f95', category: 'genel', text: 'Türk kahvesi, UNESCO Somut Olmayan Kültürel Miras Listesi’ndedir; ebru, lokum bayramı ve dede korkut da listededir.' },
  { id: 'f96', category: 'genel', text: 'Ayasofya, 537’de tamamlandığında dünyanın en büyük katedraliydi ve yaklaşık bin yıl bu unvanı korudu.' },
  { id: 'f97', category: 'genel', text: 'Bayraktar TB2, Türk savunma sanayisinin dünyada en çok tanınan ürünlerinden biridir ve 30’dan fazla ülkeye ihraç edilmiştir.' },
  { id: 'f98', category: 'genel', text: 'Dolmabahçe Sarayı’ndaki tüm saatler, Atatürk’ün vefat saati olan 09.05’te durdurulmuştur (asıl odada).' },
  { id: 'f99', category: 'genel', text: 'Türk astrofizikçi Feryal Özel, tarihte ilk kara delik fotoğrafını çeken Event Horizon Telescope ekibinin önde gelen bilim insanlarındandır.' },
  { id: 'f100', category: 'genel', text: 'TEKNOFEST, dünyanın en büyük havacılık ve teknoloji festivallerinden biridir ve her yıl Türkiye’de milyonlarca ziyaretçi ağırlar.' },
];

/** Tarihe göre günün bilgisini deterministik seçer (her gün aynı, ertesi gün değişir). */
export function getDailyFact(): DailyFact {
  const today = new Date();
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
  return DAILY_FACTS[seed % DAILY_FACTS.length];
}

export const FACT_CATEGORY_LABELS: Record<DailyFact['category'], string> = {
  tarih: 'Tarih',
  cografya: 'Coğrafya',
  vatandaslik: 'Vatandaşlık',
  genel: 'Genel Kültür',
};
