export interface Question {
  id: string;
  category: 'tarih' | 'cografya' | 'vatandaslik' | 'guncel';
  question: string;
  options: string[];
  correctIndex: number;
  difficulty: 'kolay' | 'orta' | 'zor';
  aciklama?: string;
}

export const QUESTION_POOL: Question[] = [
  // TARİH
  {
    id: 'h001',
    category: 'tarih',
    question: 'Türkiye Büyük Millet Meclisi hangi tarihte açılmıştır?',
    options: ['23 Nisan 1920', '29 Ekim 1923', '30 Ağustos 1922', '1 Kasım 1922'],
    correctIndex: 0,
    difficulty: 'kolay',
    aciklama: 'TBMM, 23 Nisan 1920\'de Ankara\'da açıldı ve millî egemenliğe dayalı yeni Türk devletinin temeli atıldı. Bu tarih bugün Ulusal Egemenlik ve Çocuk Bayramı olarak kutlanır.',
  },
  {
    id: 'h002',
    category: 'tarih',
    question: 'Lozan Antlaşması hangi yılda imzalanmıştır?',
    options: ['1920', '1921', '1923', '1925'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Lozan Barış Antlaşması 24 Temmuz 1923\'te imzalandı; yeni Türk devletinin bağımsızlığı uluslararası alanda tanındı ve kapitülasyonlar kaldırıldı.',
  },
  {
    id: 'h003',
    category: 'tarih',
    question: 'Kurtuluş Savaşı\'nda Sakarya Meydan Muharebesi hangi yılda yaşandı?',
    options: ['1919', '1920', '1921', '1922'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Sakarya Meydan Muharebesi 23 Ağustos-13 Eylül 1921\'de kazanıldı. 1683 Viyana bozgunundan beri süren geri çekilme sona erdi; bu zaferle Mustafa Kemal\'e "Gazi" unvanı ve mareşallik rütbesi verildi.',
  },
  {
    id: 'h004',
    category: 'tarih',
    question: 'Osmanlı Devleti\'nin kuruluş yılı hangisidir?',
    options: ['1071', '1176', '1299', '1453'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Osmanlı Devleti, Osman Bey önderliğinde 1299\'da Söğüt çevresinde kuruldu. Bir uç beyliğiyken zamanla üç kıtaya yayılan büyük bir imparatorluğa dönüştü.',
  },
  {
    id: 'h005',
    category: 'tarih',
    question: 'İstanbul\'un fethini gerçekleştiren Osmanlı padişahı kimdir?',
    options: ['I. Murat', 'II. Murat', 'II. Mehmet', 'I. Selim'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'İstanbul 29 Mayıs 1453\'te II. Mehmet (Fatih Sultan Mehmet) tarafından fethedildi. Bu olay Orta Çağ\'ın sonu, Yeni Çağ\'ın başlangıcı kabul edilir.',
  },
  {
    id: 'h006',
    category: 'tarih',
    question: 'Birinci Dünya Savaşı hangi olayla başlamıştır?',
    options: [
      'Almanya\'nın Fransa\'yı işgali',
      'Avusturya Veliahtı\'nın öldürülmesi',
      'Osmanlı\'nın savaşa girmesi',
      'Rusya\'nın seferberlik ilan etmesi',
    ],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'I. Dünya Savaşı, 28 Haziran 1914\'te Avusturya-Macaristan veliahtı Franz Ferdinand\'ın Saraybosna\'da bir Sırp milliyetçisi tarafından öldürülmesiyle başladı.',
  },
  {
    id: 'h007',
    category: 'tarih',
    question: 'Türkiye\'de çok partili siyasi hayat hangi yılda başlamıştır?',
    options: ['1923', '1930', '1946', '1950'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Türkiye\'de çok partili siyasi hayata geçiş 1946\'da gerçekleşti; Demokrat Parti kuruldu ve ilk kez birden fazla partinin katıldığı seçim yapıldı. 1950\'de DP iktidara geldi.',
  },
  {
    id: 'h008',
    category: 'tarih',
    question: 'Mondros Ateşkesi hangi tarihte imzalanmıştır?',
    options: ['30 Ekim 1918', '30 Kasım 1918', '11 Kasım 1918', '18 Ocak 1919'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Mondros Ateşkesi 30 Ekim 1918\'de imzalandı. Osmanlı I. Dünya Savaşı\'ndan çekildi; ağır hükümleriyle Anadolu\'nun işgaline zemin hazırladı.',
  },
  {
    id: 'h009',
    category: 'tarih',
    question: 'Türk alfabesi hangi yılda kabul edilmiştir?',
    options: ['1924', '1926', '1928', '1932'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Harf İnkılabı (Latin alfabesi) 1 Kasım 1928\'de kabul edildi; Arap alfabesi bırakılarak Türkçeye uygun Latin temelli yeni Türk alfabesine geçildi. Okuryazarlığı artırmak için Millet Mektepleri açıldı.',
  },
  {
    id: 'h010',
    category: 'tarih',
    question: 'Atatürk hangi tarihte vefat etmiştir?',
    options: ['10 Kasım 1938', '10 Kasım 1937', '19 Mayıs 1938', '29 Ekim 1938'],
    correctIndex: 0,
    difficulty: 'kolay',
    aciklama: 'Mustafa Kemal Atatürk 10 Kasım 1938\'de Dolmabahçe Sarayı\'nda vefat etti. Her yıl 10 Kasım\'da saat 09.05\'te anılır.',
  },
  {
    id: 'h011',
    category: 'tarih',
    question: 'Malazgirt Muharebesi hangi yılda gerçekleşmiştir?',
    options: ['1071', '1176', '1243', '1302'],
    correctIndex: 0,
    difficulty: 'kolay',
    aciklama: 'Malazgirt Meydan Muharebesi\'nde (26 Ağustos 1071) Sultan Alparslan, Bizans ordusunu yendi. Anadolu\'nun kapıları Türklere açıldı ve Anadolu\'nun Türkleşme süreci başladı.',
  },
  {
    id: 'h012',
    category: 'tarih',
    question: 'Misak-ı Millî hangi tarihte kabul edilmiştir?',
    options: ['Ocak 1920', 'Nisan 1920', 'Temmuz 1920', 'Ekim 1920'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Misak-ı Millî (Millî Ant), son Osmanlı Mebusan Meclisi tarafından 28 Ocak 1920\'de kabul edildi. Yeni Türk devletinin sınırlarını ve bağımsızlık ilkelerini belirleyen temel belgedir.',
  },
  {
    id: 'h013',
    category: 'tarih',
    question: 'Kurtuluş Savaşı\'nda Doğu Cephesi\'nde Ermenistan\'a karşı kazanılan zafer sonucunda imzalanan ve TBMM\'nin uluslararası alanda imzaladığı ilk antlaşma aşağıdakilerden hangisidir?',
    options: ['Gümrü Antlaşması', 'Moskova Antlaşması', 'Kars Antlaşması', 'Ankara Antlaşması'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Doğu Cephesi\'nde Kâzım Karabekir komutasında Ermenistan\'a karşı kazanılan başarının ardından 3 Aralık 1920\'de Gümrü Antlaşması imzalanmıştır. Bu, TBMM Hükûmeti\'nin imzaladığı ilk antlaşmadır. (Moskova ve Kars 1921, Ankara Antlaşması Fransa ile 1921\'dir.)',
  },
  {
    id: 'h014',
    category: 'tarih',
    question: 'Osmanlı Devleti\'nin Avrupa\'da ilk kez büyük çaplı toprak kaybettiği ve klasik dönemlendirmede "Gerileme Dönemi"nin başlangıcı olarak kabul edilen antlaşma aşağıdakilerden hangisidir?',
    options: ['Karlofça Antlaşması', 'Pasarofça Antlaşması', 'Küçük Kaynarca Antlaşması', 'Ziştovi Antlaşması'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '1699 Karlofça Antlaşması ile Osmanlı, Kutsal İttifak devletlerine (Avusturya, Venedik, Lehistan) Macaristan ve Mora gibi önemli topraklar bırakmış; ilk kez geniş çaplı toprak kaybetmiştir. Bu antlaşma Duraklama Dönemi\'nin sonu, Gerileme Dönemi\'nin başlangıcı sayılır.',
  },
  {
    id: 'h015',
    category: 'tarih',
    question: '"Türk" adını resmî devlet adı olarak kullanan ilk Türk devleti aşağıdakilerden hangisidir?',
    options: ['Asya Hun Devleti', 'Göktürk (Kök Türk) Devleti', 'Uygur Devleti', 'Avar Devleti'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: '"Türk" sözcüğünü ilk kez resmî devlet adı olarak Göktürkler (Kök Türkler) kullanmıştır. Ayrıca Türk adının geçtiği ilk yazılı Türkçe belgeler olan Orhun (Göktürk) Yazıtları da bu döneme aittir.',
  },
  {
    id: 'h016',
    category: 'tarih',
    question: 'Türkiye\'de kadınlara milletvekili seçme ve seçilme hakkı hangi yıl tanınmıştır?',
    options: ['1930', '1933', '1934', '1935'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Kadınlara siyasi haklar kademeli verilmiştir: 1930\'da belediye seçimlerine katılma, 1933\'te muhtar seçme-seçilme, 5 Aralık 1934\'te ise milletvekili seçme ve seçilme hakkı tanınmıştır. Türkiye, kadınlara bu hakkı pek çok Avrupa ülkesinden önce vermiştir.',
  },
  {
    id: 'h017',
    category: 'tarih',
    question: '751 Talas Savaşı\'nın Türk-İslam tarihi açısından en önemli sonucu aşağıdakilerden hangisidir?',
    options: [
      'Türklerin kitleler hâlinde İslamiyet\'i kabul etmeye başlaması',
      'Abbasi Devleti\'nin yıkılması',
      'Anadolu\'nun kapılarının Türklere açılması',
      'Emevi Devleti\'nin kurulması',
    ],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '751 Talas Savaşı\'nda Abbasiler ile Çinliler karşı karşıya geldi; Karluk Türklerinin Abbasileri desteklemesiyle savaşı Müslümanlar kazandı. Sonrasında Türk-Arap ilişkileri yumuşadı ve Türkler kitleler hâlinde İslamiyet\'i kabul etmeye başladı. "Anadolu\'nun kapılarının açılması" ise 1071 Malazgirt\'in sonucudur.',
  },
  {
    id: 'h018',
    category: 'tarih',
    question: 'Osmanlı Devleti\'nde Yeniçeri Ocağı hangi padişah döneminde kurulmuştur?',
    options: ['Orhan Bey', 'I. Murat (Hüdavendigâr)', 'Yıldırım Bayezid', 'I. Mehmet (Çelebi)'],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Yeniçeri Ocağı, devşirme sistemine dayalı olarak I. Murat (Hüdavendigâr) döneminde kurulmuştur. Sık karıştırılır: Osmanlı\'nın ilk düzenli ordusu olan "yaya ve müsellemler" ise Orhan Bey dönemindedir.',
  },
  {
    id: 'h019',
    category: 'tarih',
    question: 'Lozan Antlaşması\'nda çözüme kavuşturulamayıp sonraya bırakılan ve 1926\'da Türkiye aleyhine (İngiltere/Irak lehine) sonuçlanan sorun aşağıdakilerden hangisidir?',
    options: ['Musul Sorunu', 'Hatay Sorunu', 'Boğazlar Sorunu', 'Nüfus Mübadelesi'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Lozan\'da Musul sorunu çözülemedi ve İngiltere ile ikili görüşmeye bırakıldı. 1926 Ankara Antlaşması ile Musul, İngiliz mandasındaki Irak\'a bırakıldı. Boğazlar 1936 Montrö, Hatay 1939\'da çözüldü; nüfus mübadelesi ise Lozan\'da karara bağlandı.',
  },
  {
    id: 'h020',
    category: 'tarih',
    question: '3 Mart 1924\'te kabul edilen Tevhid-i Tedrisat (Öğretim Birliği) Kanunu\'nun temel amacı aşağıdakilerden hangisidir?',
    options: [
      'Tüm eğitim kurumlarını Millî Eğitim Bakanlığı çatısı altında toplamak',
      'Latin harflerine geçmek',
      'İlk Türk üniversitesini kurmak',
      'Kapitülasyonları kaldırmak',
    ],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Tevhid-i Tedrisat Kanunu (3 Mart 1924) ile ülkedeki bütün okullar Millî Eğitim Bakanlığı\'na bağlanmış, medreseler kapatılmış ve eğitimde birlik sağlanmıştır. Laik ve millî eğitimin temelini atan inkılaptır. Aynı gün halifelik de kaldırılmıştır.',
  },
  {
    id: 'h021',
    category: 'tarih',
    question: '1176 Miryokefalon (Myriokephalon) Savaşı\'nın Türk tarihi açısından en önemli sonucu aşağıdakilerden hangisidir?',
    options: [
      'Anadolu\'nun kesin olarak Türk yurdu olduğunun kanıtlanması',
      'Bizans\'ın İstanbul\'u kaybetmesi',
      'Haçlı Seferleri\'nin başlaması',
      'Anadolu Selçuklu Devleti\'nin kurulması',
    ],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '1176 Miryokefalon Savaşı\'nda Anadolu Selçuklu Sultanı II. Kılıç Arslan, Bizans İmparatoru Manuel\'i yendi. Bu zaferle Bizans\'ın Anadolu\'yu geri alma umudu bitti; Anadolu kesin olarak Türk yurdu kabul edildi. Sık vurgulanır: Malazgirt (1071) Anadolu\'nun kapılarını açtı, Miryokefalon (1176) bunu kesinleştirdi.',
  },
  {
    id: 'h022',
    category: 'tarih',
    question: 'Türkiye\'nin Boğazlar üzerindeki egemenlik haklarını yeniden tam olarak kazanmasını sağlayan ve günümüzde hâlâ yürürlükte olan 1936 tarihli sözleşme aşağıdakilerden hangisidir?',
    options: ['Montrö Boğazlar Sözleşmesi', 'Lozan Boğazlar Sözleşmesi', 'Balkan Antantı', 'Sadabat Paktı'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '1936 Montrö Boğazlar Sözleşmesi ile Lozan\'da kurulan ve Boğazları kısıtlayan uluslararası komisyon kaldırıldı; Boğazların yönetimi ve askerî egemenliği tamamen Türkiye\'ye geçti. Sözleşme hâlâ yürürlüktedir. (Balkan Antantı 1934, Sadabat Paktı 1937 tarihli güvenlik antlaşmalarıdır.)',
  },
  {
    id: 'h023',
    category: 'tarih',
    question: 'Yeni Türk Devleti\'nin izleyeceği ekonomi politikalarının belirlendiği ve "Misak-ı İktisadî" (Ekonomi Andı) kararlarının alındığı kongre aşağıdakilerden hangisidir?',
    options: ['İzmir İktisat Kongresi', 'Sivas Kongresi', 'Erzurum Kongresi', 'Balıkesir Kongresi'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '1923 İzmir İktisat Kongresi\'nde milli ekonomiyi geliştirme kararları ("Misak-ı İktisadî") alındı; yerli üretim ve özel teşebbüs desteklendi. Lozan görüşmelerine ara verilen dönemde toplanmıştır. Sivas ve Erzurum, Kurtuluş Savaşı hazırlık dönemi kongreleridir.',
  },
  {
    id: 'h024',
    category: 'tarih',
    question: 'Kurtuluş Savaşı\'nın askerî safhasını sona erdiren ve 30 Ağustos 1922\'de Yunan ordusuna karşı kazanılan kesin zafer aşağıdakilerden hangisidir?',
    options: [
      'Başkomutanlık Meydan Muharebesi (Büyük Taarruz)',
      'I. İnönü Muharebesi',
      'Sakarya Meydan Muharebesi',
      'Kütahya-Eskişehir Muharebeleri',
    ],
    correctIndex: 0,
    difficulty: 'kolay',
    aciklama: '30 Ağustos 1922 Başkomutanlık Meydan Muharebesi (Büyük Taarruz) ile Yunan ordusu kesin yenilgiye uğratıldı ve savaşın askerî safhası sona erdi. Ardından Mudanya Ateşkesi (11 Ekim 1922) imzalandı. 30 Ağustos bugün Zafer Bayramı olarak kutlanır.',
  },
  {
  id: 'h025',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi I. TBMM döneminde kabul edilen kanunlardan biri değildir?',
  options: [
    'Hıyanet-i Vataniye Kanunu',
    'Men-i Müskirat Kanunu',
    'Tevhid-i Tedrisat Kanunu',
    'İstiklal Mahkemeleri Kanunu'
  ],
  correctIndex: 2,
  difficulty: 'orta',
  aciklama: 'Tevhid-i Tedrisat Kanunu 3 Mart 1924 tarihinde, yani Cumhuriyet döneminde kabul edilmiştir. Hıyanet-i Vataniye Kanunu, Men-i Müskirat Kanunu ve İstiklal Mahkemeleri Kanunu ise I. TBMM döneminde çıkarılan kanunlardandır.',
},
{
  id: 'h026',
  category: 'tarih',
  question: 'Amasya Genelgesi’nde yer alan “Milletin bağımsızlığını yine milletin azim ve kararı kurtaracaktır.” maddesi aşağıdaki ilkelerden hangisini doğrudan vurgular?',
  options: [
    'Ulusal egemenlik',
    'Laiklik',
    'Devletçilik',
    'İnkılapçılık'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Bu madde, kurtuluşun padişah ya da manda yönetimiyle değil, doğrudan milletin iradesiyle gerçekleşeceğini ifade eder. Bu nedenle ulusal egemenlik anlayışını vurgular.',
},
{
  id: 'h027',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Erzurum Kongresi’nde alınan kararlardan biri değildir?',
  options: [
    'Manda ve himaye kabul edilemez.',
    'Millî sınırlar içinde vatan bir bütündür, parçalanamaz.',
    'Temsil Heyeti tüm yurdu temsil eder hâle getirilmiştir.',
    'Kuva-yı Milliye’yi etkin, millî iradeyi hâkim kılmak esastır.'
  ],
  correctIndex: 2,
  difficulty: 'orta',
  aciklama: 'Temsil Heyeti’nin tüm yurdu temsil eder hâle getirilmesi Sivas Kongresi’nde gerçekleşmiştir. Erzurum Kongresi’nde ise Temsil Heyeti doğu illerini temsil etmek üzere oluşturulmuştur.',
},
{
  id: 'h028',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Osmanlı Devleti’nde padişahın yetkilerini ilk kez sınırlayan belge olarak kabul edilir?',
  options: [
    'Sened-i İttifak',
    'Tanzimat Fermanı',
    'Islahat Fermanı',
    'Kanun-ı Esasi'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: '1808 Sened-i İttifak, Osmanlı tarihinde padişahın yetkilerini ilk kez sınırlayan belge olarak kabul edilir. Bu belge padişah ile ayanlar arasında imzalanmıştır. Tanzimat Fermanı hukuk devleti anlayışına, Kanun-ı Esasi ise anayasal düzene geçişe örnektir.',
},
{
  id: 'h029',
  category: 'tarih',
  question: 'Osmanlı Devleti’nde ilk Türk matbaasının kurulmasına izin verilen dönem aşağıdakilerden hangisidir?',
  options: [
    'Lale Devri',
    'Tanzimat Dönemi',
    'I. Meşrutiyet Dönemi',
    'II. Meşrutiyet Dönemi'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Osmanlı Devleti’nde ilk Türk matbaası, Lale Devri’nde İbrahim Müteferrika ve Sait Efendi tarafından kurulmuştur. Matbaada dinî eserlerin basımına başlangıçta izin verilmemiştir.',
},
{
  id: 'h030',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Osmanlı Devleti’nde askerî alanda yapılan ıslahatlardan biri değildir?',
  options: [
    'Nizam-ı Cedit Ordusu’nun kurulması',
    'Sekban-ı Cedit Ordusu’nun kurulması',
    'Asakir-i Mansure-i Muhammediye Ordusu’nun kurulması',
    'Düyun-u Umumiye İdaresi’nin kurulması'
  ],
  correctIndex: 3,
  difficulty: 'orta',
  aciklama: 'Düyun-u Umumiye İdaresi, Osmanlı dış borçlarının alacaklı devletler tarafından denetlenmesi amacıyla kurulmuş mali bir kurumdur. Diğer seçenekler askerî alanda yapılan ıslahatlara örnektir.',
},
{
  id: 'h031',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Kurtuluş Savaşı Hazırlık Dönemi gelişmelerinden biri değildir?',
  options: [
    'Amasya Genelgesi’nin yayımlanması',
    'Erzurum Kongresi’nin toplanması',
    'Sivas Kongresi’nin toplanması',
    'Mudanya Ateşkes Antlaşması’nın imzalanması'
  ],
  correctIndex: 3,
  difficulty: 'orta',
  aciklama: 'Mudanya Ateşkes Antlaşması 11 Ekim 1922’de imzalanmış olup Kurtuluş Savaşı’nın askerî safhasından sonra gerçekleşmiştir. Amasya Genelgesi, Erzurum Kongresi ve Sivas Kongresi ise Hazırlık Dönemi gelişmeleridir.',
},
{
  id: 'h032',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi I. İnönü Muharebesi’nin sonuçlarından biri değildir?',
  options: [
    'Londra Konferansı’nın toplanması',
    'İstiklal Marşı’nın kabul edilmesi',
    'Moskova Antlaşması’nın imzalanması',
    'Tekâlif-i Milliye Emirleri’nin yayımlanması'
  ],
  correctIndex: 3,
  difficulty: 'orta',
  aciklama: 'Tekâlif-i Milliye Emirleri, Sakarya Meydan Muharebesi öncesinde ordunun ihtiyaçlarını karşılamak amacıyla yayımlanmıştır. Londra Konferansı, İstiklal Marşı’nın kabulü ve Moskova Antlaşması ise I. İnönü Muharebesi sonrasında yaşanan gelişmelerdendir.',
},
{
  id: 'h033',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Tekâlif-i Milliye Emirleri’nin yayımlanma amacını en doğru şekilde ifade eder?',
  options: [
    'Ordunun ihtiyaçlarını halk desteğiyle karşılamak',
    'Saltanat yönetimini hukuken sona erdirmek',
    'Kapitülasyonları tamamen kaldırmak',
    'Doğu Cephesi’ndeki savaşı sona erdirmek'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Tekâlif-i Milliye Emirleri, Sakarya Meydan Muharebesi öncesinde ordunun yiyecek, giyecek, taşıt ve silah gibi ihtiyaçlarını karşılamak amacıyla yayımlanmıştır. Bu emirler, topyekûn mücadele anlayışının önemli örneklerindendir.',
},
{
  id: 'h034',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Mudanya Ateşkes Antlaşması’nın sonuçlarından biridir?',
  options: [
    'Doğu Trakya’nın savaş yapılmadan Türkiye’ye bırakılması',
    'Kapitülasyonların tamamen kaldırılması',
    'Musul Sorunu’nun Türkiye lehine çözülmesi',
    'Boğazların yönetiminin tamamen Türkiye’ye geçmesi'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Mudanya Ateşkes Antlaşması ile Doğu Trakya savaş yapılmadan Türkiye’ye bırakılmıştır. Kapitülasyonların kaldırılması Lozan Antlaşması’yla, Boğazların tam egemenliğinin sağlanması ise 1936 Montrö Boğazlar Sözleşmesi’yle gerçekleşmiştir.',
},
{
  id: 'h035',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Atatürk Dönemi dış politika gelişmelerinden biri değildir?',
  options: [
    'Balkan Antantı’nın imzalanması',
    'Sadabat Paktı’nın imzalanması',
    'Montrö Boğazlar Sözleşmesi’nin imzalanması',
    'Türkiye’nin NATO’ya üye olması'
  ],
  correctIndex: 3,
  difficulty: 'orta',
  aciklama: 'Türkiye’nin NATO’ya üyeliği 1952 yılında gerçekleşmiştir ve Atatürk Dönemi gelişmesi değildir. Balkan Antantı 1934, Montrö Boğazlar Sözleşmesi 1936, Sadabat Paktı ise 1937’de imzalanmıştır.',
},
{
  id: 'h036',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Cumhuriyetçilik ilkesiyle doğrudan ilişkilidir?',
  options: [
    'Egemenliğin millete ait olması',
    'Devletin ekonomiye yön vermesi',
    'Din ve devlet işlerinin ayrılması',
    'Çağın gereklerine göre yenilik yapılması'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Cumhuriyetçilik ilkesi, egemenliğin bir kişi veya hanedana değil millete ait olmasını ifade eder. Devletçilik ekonomiyle, laiklik din-devlet ayrımıyla, inkılapçılık ise çağdaşlaşma ve yenilik anlayışıyla ilgilidir.',
},
{
  id: 'h037',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Halkçılık ilkesinin temel amaçlarından biridir?',
  options: [
    'Sınıf ayrımını reddederek toplumda eşitliği sağlamak',
    'Devletin ekonomik yatırımları bizzat yürütmesi',
    'Devlet yönetiminde din kurallarını esas almak',
    'Saltanat yönetimini güçlendirmek'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Halkçılık ilkesi, toplumda ayrıcalıklı sınıfların bulunmamasını ve herkesin kanun önünde eşit olmasını savunur. Devletin ekonomik yatırımları yürütmesi devletçilikle, din kurallarının devlet yönetiminde esas alınmaması ise laiklikle ilgilidir.',
},
{
  id: 'h038',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Laiklik ilkesinin doğrudan sonuçlarından biridir?',
  options: [
    'Halifeliğin kaldırılması',
    'Aşar vergisinin kaldırılması',
    'Kabotaj Kanunu’nun kabul edilmesi',
    'Soyadı Kanunu’nun çıkarılması'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Halifeliğin kaldırılması, devlet yönetiminde dinî otoritenin etkisini sona erdirmeye yönelik bir gelişmedir ve laiklik ilkesiyle doğrudan ilişkilidir. Aşar vergisinin kaldırılması ekonomik, Kabotaj Kanunu milliyetçilik, Soyadı Kanunu ise toplumsal düzenlemeyle ilgilidir.',
},
{
  id: 'h039',
  category: 'tarih',
  question: 'Aşağıdakilerden hangisi Cumhuriyet Dönemi’nde eğitim ve kültür alanında yapılan inkılaplardan biri değildir?',
  options: [
    'Millet Mekteplerinin açılması',
    'Türk Dil Kurumu’nun kurulması',
    'Tevhid-i Tedrisat Kanunu’nun kabul edilmesi',
    'Kabotaj Kanunu’nun kabul edilmesi'
  ],
  correctIndex: 3,
  difficulty: 'orta',
  aciklama: 'Kabotaj Kanunu, Türkiye’nin kendi kara sularında yolcu ve yük taşıma hakkını Türk vatandaşlarına bırakmasıyla ilgilidir ve ekonomi/bağımsızlık alanında değerlendirilir. Millet Mektepleri, Türk Dil Kurumu ve Tevhid-i Tedrisat ise eğitim-kültür alanındaki gelişmelerdendir.',
},
  // COĞRAFYA
  {
    id: 'c001',
    category: 'cografya',
    question: 'Türkiye\'nin en uzun nehri hangisidir?',
    options: ['Fırat', 'Dicle', 'Kızılırmak', 'Sakarya'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Kızılırmak (~1355 km), tamamen Türkiye sınırları içinde akan en uzun nehirdir; Sivas yakınlarından doğup Karadeniz\'e dökülür.',
  },
  {
    id: 'c002',
    category: 'cografya',
    question: 'Türkiye\'nin en yüksek dağı hangisidir?',
    options: ['Erciyes', 'Ağrı', 'Kaçkar', 'Uludağ'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'Ağrı Dağı 5137 m ile Türkiye\'nin en yüksek dağıdır; Doğu Anadolu\'da yer alan volkanik kökenli bir dağdır.',
  },
  {
    id: 'c003',
    category: 'cografya',
    question: 'Türkiye kaç komşu ülkeyle sınır paylaşmaktadır?',
    options: ['6', '7', '8', '9'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Türkiye\'nin 8 komşusu vardır: Yunanistan, Bulgaristan, Gürcistan, Ermenistan, Azerbaycan (Nahçıvan), İran, Irak ve Suriye.',
  },
  {
    id: 'c004',
    category: 'cografya',
    question: 'Marmara Denizi hangi iki denizi birbirine bağlar?',
    options: [
      'Karadeniz – Akdeniz',
      'Karadeniz – Ege Denizi',
      'Ege Denizi – Akdeniz',
      'Karadeniz – Kızıldeniz',
    ],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'Marmara Denizi, İstanbul ve Çanakkale boğazları aracılığıyla Karadeniz ile Ege Denizi\'ni birbirine bağlar.',
  },
  {
    id: 'c005',
    category: 'cografya',
    question: 'Türkiye\'nin en büyük gölü hangisidir?',
    options: ['Eğirdir Gölü', 'Van Gölü', 'Tuz Gölü', 'Beyşehir Gölü'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'Van Gölü (~3713 km²), Türkiye\'nin en büyük gölüdür; sodalı (acı) suyuyla bilinir ve Doğu Anadolu\'da yer alır.',
  },
  {
    id: 'c006',
    category: 'cografya',
    question: 'Karadeniz ikliminin en belirgin özelliği hangisidir?',
    options: [
      'Az yağışlı ve sıcak yazlar',
      'Her mevsim yağışlı',
      'Kışlar ılık, yazlar serin',
      'Kurak yazlar, bol yağışlı kışlar',
    ],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Karadeniz ikliminin en belirgin özelliği her mevsim yağış almasıdır; bu nedenle bölge gür ormanlarla kaplıdır.',
  },
  {
    id: 'c007',
    category: 'cografya',
    question: 'Türkiye hangi yarımkürededir?',
    options: [
      'Kuzey ve Doğu yarımküre',
      'Güney ve Doğu yarımküre',
      'Kuzey ve Batı yarımküre',
      'Güney ve Batı yarımküre',
    ],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Türkiye, Ekvator\'un kuzeyinde (Kuzey yarımküre) ve Greenwich meridyeninin doğusunda (Doğu yarımküre) yer alır.',
  },
  {
    id: 'c008',
    category: 'cografya',
    question: 'Boğaziçi Köprüsü hangi şehirde yer almaktadır?',
    options: ['Ankara', 'İzmir', 'İstanbul', 'Bursa'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Boğaziçi (15 Temmuz Şehitler) Köprüsü İstanbul\'dadır ve Asya ile Avrupa yakalarını birbirine bağlar.',
  },
  {
    id: 'c009',
    category: 'cografya',
    question: 'Türkiye\'nin başkenti neresidir?',
    options: ['İstanbul', 'İzmir', 'Bursa', 'Ankara'],
    correctIndex: 3,
    difficulty: 'kolay',
    aciklama: 'Türkiye\'nin başkenti Ankara\'dır; 13 Ekim 1923\'te başkent ilan edilmiştir.',
  },
  {
    id: 'c010',
    category: 'cografya',
    question: 'Fırat ve Dicle nehirleri hangi denize dökülür?',
    options: ['Karadeniz', 'Hazar Denizi', 'Pers Körfezi', 'Kızıldeniz'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Fırat ve Dicle nehirleri Şattülarap\'ta birleşerek Basra (Pers) Körfezi\'ne dökülür.',
  },
  {
    id: 'c011',
    category: 'cografya',
    question: 'Türkiye\'nin yüzölçümü yaklaşık kaç km²\'dir?',
    options: ['580.000', '680.000', '780.000', '880.000'],
    correctIndex: 2,
    difficulty: 'zor',
    aciklama: 'Türkiye\'nin yüzölçümü yaklaşık 780.000 km²\'dir (göller dahil ~783.562 km²).',
  },
  {
    id: 'c012',
    category: 'cografya',
    question: 'Anadolu yarımadasını Avrupa\'dan ayıran boğaz hangisidir?',
    options: ['Çanakkale Boğazı', 'İstanbul Boğazı', 'Hürmüz Boğazı', 'Kıbrıs Boğazı'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'İstanbul Boğazı, Anadolu (Asya) yakasını Avrupa (Trakya) yakasından ayırır ve Karadeniz\'i Marmara Denizi\'ne bağlar.',
  },
  {
  id: 'c013',
  category: 'cografya',
  question: 'Türkiye’de gerçek alan ile izdüşüm alan arasındaki farkın fazla olması aşağıdakilerden hangisinin sonucudur?',
  options: [
    'Dağlık ve engebeli arazinin fazla olması',
    'Üç tarafının denizlerle çevrili olması',
    'Orta kuşakta yer alması',
    'Doğu-batı yönünde geniş yer kaplaması'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Gerçek alan, yer şekillerinin engebesi dikkate alınarak hesaplanan alandır. İzdüşüm alan ise arazi düz kabul edilerek hesaplanır. Türkiye’de dağlık ve engebeli alanlar fazla olduğu için gerçek alan ile izdüşüm alan arasındaki fark fazladır.',
},
{
  id: 'c014',
  category: 'cografya',
  question: 'Türkiye’de dağların kuzey-güney yönlü ulaşımı zorlaştırmasının temel nedeni aşağıdakilerden hangisidir?',
  options: [
    'Dağların genel olarak doğu-batı doğrultusunda uzanması',
    'Türkiye’nin orta kuşakta yer alması',
    'Akarsuların denge profiline ulaşmamış olması',
    'Kıyı uzunluğunun fazla olması'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Türkiye’de özellikle Kuzey Anadolu ve Toros Dağları genel olarak doğu-batı doğrultusunda uzanır. Bu durum kuzey-güney yönlü ulaşımı zorlaştırır, kıyı ile iç kesimler arasındaki bağlantıyı sınırlar.',
},
{
  id: 'c015',
  category: 'cografya',
  question: 'Türkiye’de kıyı ile iç kesimler arasındaki sıcaklık ve yağış farkının Karadeniz ve Akdeniz kıyılarında belirgin olmasının temel nedeni aşağıdakilerden hangisidir?',
  options: [
    'Dağların kıyıya paralel uzanması',
    'Akarsuların kısa boylu olması',
    'Kıyılarda nüfus yoğunluğunun fazla olması',
    'Türkiye’nin doğu-batı yönünde geniş olması'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Karadeniz ve Akdeniz kıyılarında dağlar kıyıya paralel uzandığı için deniz etkisi iç kesimlere fazla sokulamaz. Bu nedenle kıyı ile iç kesimler arasında sıcaklık ve yağış farkı belirginleşir.',
},
{
  id: 'c016',
  category: 'cografya',
  question: 'Türkiye’de Ege kıyılarında girinti ve çıkıntının fazla olmasının temel nedeni aşağıdakilerden hangisidir?',
  options: [
    'Dağların kıyıya dik uzanması',
    'Karstik arazilerin geniş yer kaplaması',
    'Volkanik dağların yaygın olması',
    'Akarsu rejimlerinin düzensiz olması'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Ege Bölgesi’nde dağlar kıyıya dik uzandığı için deniz iç kesimlere sokulmuş, kıyıda girinti ve çıkıntı artmıştır. Bu durum doğal limanların fazla olmasına ve deniz etkisinin iç kesimlere daha kolay ulaşmasına neden olur.',
},
{
  id: 'c017',
  category: 'cografya',
  question: 'Türkiye’de yaz kuraklığının en belirgin görüldüğü iklim tipi aşağıdakilerden hangisidir?',
  options: [
    'Akdeniz iklimi',
    'Karadeniz iklimi',
    'Sert karasal iklim',
    'Ilıman okyanusal iklim'
  ],
  correctIndex: 0,
  difficulty: 'kolay',
  aciklama: 'Akdeniz ikliminde yazlar sıcak ve kurak, kışlar ılık ve yağışlı geçer. Bu nedenle Türkiye’de yaz kuraklığının en belirgin görüldüğü iklim tipi Akdeniz iklimidir.',
},
{
  id: 'c018',
  category: 'cografya',
  question: 'Türkiye’de akarsuların hidroelektrik enerji potansiyelinin yüksek olmasında aşağıdakilerden hangisi daha çok etkilidir?',
  options: [
    'Yatak eğimlerinin fazla olması',
    'Rejimlerinin düzenli olması',
    'Boylarının çok uzun olması',
    'Denge profiline ulaşmış olmaları'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Türkiye’de yer şekilleri engebeli olduğu için akarsuların yatak eğimleri fazladır. Bu durum akış hızını ve hidroelektrik enerji potansiyelini artırır. Ancak akarsu rejimlerinin düzensiz olması enerji üretimini yıl içinde dalgalandırabilir.',
},
{
  id: 'c019',
  category: 'cografya',
  question: 'Türkiye’de karstik şekillerin en yaygın görüldüğü bölge aşağıdakilerden hangisidir?',
  options: [
    'Akdeniz Bölgesi',
    'Karadeniz Bölgesi',
    'Marmara Bölgesi',
    'Güneydoğu Anadolu Bölgesi'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Karstik şekiller, kalker, jips ve kaya tuzu gibi kolay çözünebilen kayaçların bulunduğu alanlarda oluşur. Türkiye’de karstik şekiller en yaygın olarak Akdeniz Bölgesi’nde, özellikle Toroslar çevresinde görülür.',
},
{
  id: 'c020',
  category: 'cografya',
  question: 'Türkiye’de delta ovalarının oluşabilmesi için aşağıdakilerden hangisi gerekli koşullardan biri değildir?',
  options: [
    'Akarsuyun bol miktarda alüvyon taşıması',
    'Kıyıda gelgit etkisinin az olması',
    'Kıta sahanlığının geniş olması',
    'Kıyıda dağların denize paralel uzanması'
  ],
  correctIndex: 3,
  difficulty: 'orta',
  aciklama: 'Delta ovalarının oluşması için akarsuyun bol alüvyon taşıması, kıta sahanlığının geniş olması ve kıyıda gelgit etkisinin az olması gerekir. Dağların denize paralel uzanması delta oluşumu için zorunlu bir koşul değildir.',
},
{
  id: 'c021',
  category: 'cografya',
  question: 'Türkiye’de nüfusun kıyı kesimlerde iç kesimlere göre daha yoğun olmasında aşağıdakilerden hangisi daha çok etkilidir?',
  options: [
    'İklim koşullarının daha elverişli olması',
    'Yükseltinin fazla olması',
    'Karasal iklimin yaygın olması',
    'Tarım alanlarının tamamen düz olması'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Türkiye’de kıyı kesimlerde iklim daha ılıman, ulaşım ve ekonomik faaliyetler daha gelişmiştir. Bu nedenle nüfus yoğunluğu iç kesimlere göre genellikle daha fazladır.',
},
{
  id: 'c022',
  category: 'cografya',
  question: 'Türkiye’de tarımda sulama ihtiyacının en fazla olduğu bölgelerden biri aşağıdakilerden hangisidir?',
  options: [
    'Güneydoğu Anadolu Bölgesi',
    'Karadeniz Bölgesi',
    'Marmara Bölgesi',
    'Doğu Karadeniz Bölümü'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Güneydoğu Anadolu Bölgesi’nde yaz kuraklığı belirgindir ve buharlaşma fazladır. Bu nedenle tarımda sulama ihtiyacı yüksektir. GAP ile bölgede sulama imkânlarının artırılması amaçlanmıştır.',
},
  // VATANDAŞLIK
  {
    id: 'v001',
    category: 'vatandaslik',
    question: 'Türkiye Cumhuriyeti Anayasası kaçıncı maddede devletin niteliklerini belirtir?',
    options: ['1. Madde', '2. Madde', '3. Madde', '4. Madde'],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Anayasa\'nın 2. maddesi devletin niteliklerini sayar: demokratik, laik, sosyal bir hukuk devleti. (1. madde yönetim şeklinin Cumhuriyet olduğunu belirtir.)',
  },
  {
    id: 'v002',
    category: 'vatandaslik',
    question: 'TBMM kaç üyeden oluşmaktadır?',
    options: ['450', '500', '550', '600'],
    correctIndex: 3,
    difficulty: 'orta',
    aciklama: '2017 Anayasa değişikliğiyle TBMM\'nin milletvekili sayısı 550\'den 600\'e çıkarılmıştır.',
  },
  {
    id: 'v003',
    category: 'vatandaslik',
    question: 'Türkiye\'de oy kullanma yaşı kaçtır?',
    options: ['16', '17', '18', '21'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Türkiye\'de seçme (oy kullanma) yaşı 18\'dir.',
  },
  {
    id: 'v004',
    category: 'vatandaslik',
    question: 'Cumhurbaşkanlığı görevi kaç yıllık dönemler için geçerlidir?',
    options: ['4 yıl', '5 yıl', '6 yıl', '7 yıl'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'Cumhurbaşkanı 5 yıllık dönemler için seçilir ve en fazla iki dönem görev yapabilir.',
  },
  {
    id: 'v005',
    category: 'vatandaslik',
    question: 'Anayasa Mahkemesi\'nin görevi nedir?',
    options: [
      'Vergi uyuşmazlıklarını çözmek',
      'Kanunların anayasaya uygunluğunu denetlemek',
      'Milletvekili seçimlerini yönetmek',
      'İdari davaları karara bağlamak',
    ],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Anayasa Mahkemesi\'nin temel görevi, kanunların ve bazı düzenlemelerin Anayasa\'ya uygunluğunu denetlemektir.',
  },
  {
    id: 'v006',
    category: 'vatandaslik',
    question: 'Türkiye\'nin mevcut anayasası hangi yılda yürürlüğe girmiştir?',
    options: ['1961', '1971', '1980', '1982'],
    correctIndex: 3,
    difficulty: 'kolay',
    aciklama: 'Türkiye\'nin yürürlükteki anayasası 1982 Anayasası\'dır; 7 Kasım 1982\'de halkoyuyla kabul edilmiştir.',
  },
  {
    id: 'v007',
    category: 'vatandaslik',
    question: 'Türkiye\'de hangi mahkeme idari davaları çözer?',
    options: ['Yargıtay', 'Danıştay', 'Anayasa Mahkemesi', 'Sayıştay'],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'İdari davalara bakan yüksek mahkeme Danıştay\'dır. Yargıtay ise adli (hukuk ve ceza) davalara bakar.',
  },
  {
    id: 'v008',
    category: 'vatandaslik',
    question: 'Türkiye Büyük Millet Meclisi\'nin olağan toplantı dönemi ne zamandır?',
    options: ['Ocak-Haziran', 'Ekim-Temmuz', 'Mart-Ekim', 'Nisan-Eylül'],
    correctIndex: 1,
    difficulty: 'zor',
    aciklama: 'TBMM, Anayasa gereği her yıl Ekim ayının ilk günü kendiliğinden toplanır ve genellikle Temmuz başında tatile girer.',
  },
  {
    id: 'v009',
    category: 'vatandaslik',
    question: 'Türkiye\'de devletin resmi dili nedir?',
    options: ['Kürtçe', 'Arapça', 'Türkçe', 'Osmanlıca'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Anayasa\'ya göre Türkiye Cumhuriyeti\'nin resmî dili Türkçedir.',
  },
  {
    id: 'v010',
    category: 'vatandaslik',
    question: 'Cumhurbaşkanı en fazla kaç dönem görev yapabilir?',
    options: ['1 dönem', '2 dönem', '3 dönem', 'Sınır yok'],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Cumhurbaşkanı en fazla iki dönem (her biri 5 yıl) görev yapabilir.',
  },
  {
    id: 'v011',
    category: 'vatandaslik',
    question: 'Türkiye\'de hangi organ kanun yapma yetkisine sahiptir?',
    options: ['Cumhurbaşkanlığı', 'Bakanlar Kurulu', 'TBMM', 'Danıştay'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Yasama yetkisi, yani kanun yapma yetkisi, Türk Milleti adına Türkiye Büyük Millet Meclisi\'ne aittir ve devredilemez.',
  },
  {
    id: 'v012',
    category: 'vatandaslik',
    question: 'Türkiye hangi yılda BM\'ye üye olmuştur?',
    options: ['1945', '1946', '1948', '1952'],
    correctIndex: 0,
    difficulty: 'zor',
    aciklama: 'Türkiye, Birleşmiş Milletler\'in kurucu üyelerindendir ve 1945\'te BM\'ye üye olmuştur.',
  },
  {
  id: 'v013',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre yasama yetkisi aşağıdakilerden hangisine aittir?',
  options: [
    'Cumhurbaşkanına',
    'Türkiye Büyük Millet Meclisine',
    'Anayasa Mahkemesine',
    'Danıştaya'
  ],
  correctIndex: 1,
  difficulty: 'kolay',
  aciklama: '1982 Anayasası’na göre yasama yetkisi Türk Milleti adına Türkiye Büyük Millet Meclisine aittir. Bu yetki devredilemez.',
},
{
  id: 'v014',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre yürütme yetkisi ve görevi aşağıdakilerden hangisine aittir?',
  options: [
    'Türkiye Büyük Millet Meclisine',
    'Cumhurbaşkanına',
    'Anayasa Mahkemesine',
    'Danıştaya'
  ],
  correctIndex: 1,
  difficulty: 'kolay',
  aciklama: '1982 Anayasası’na göre yürütme yetkisi ve görevi Cumhurbaşkanı tarafından, Anayasa’ya ve kanunlara uygun olarak kullanılır ve yerine getirilir.',
},
{
  id: 'v015',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre yargı yetkisi aşağıdakilerden hangisi tarafından kullanılır?',
  options: [
    'Bağımsız ve tarafsız mahkemeler',
    'Türkiye Büyük Millet Meclisi',
    'Cumhurbaşkanlığı Kabinesi',
    'Hâkimler ve Savcılar Kurulu'
  ],
  correctIndex: 0,
  difficulty: 'kolay',
  aciklama: '1982 Anayasası’na göre yargı yetkisi, Türk Milleti adına bağımsız ve tarafsız mahkemeler tarafından kullanılır.',
},{
  id: 'v016',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre kanun koymak, değiştirmek ve kaldırmak aşağıdakilerden hangisinin görev ve yetkilerindendir?',
  options: [
    'Cumhurbaşkanı',
    'Türkiye Büyük Millet Meclisi',
    'Anayasa Mahkemesi',
    'Danıştay'
  ],
  correctIndex: 1,
  difficulty: 'kolay',
  aciklama: 'Kanun koymak, değiştirmek ve kaldırmak TBMM’nin görev ve yetkileri arasındadır. Bu durum yasama yetkisinin TBMM’ye ait olmasının doğal sonucudur.',
},
{
  id: 'v017',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre Cumhurbaşkanlığı kararnameleriyle ilgili aşağıdakilerden hangisi doğrudur?',
  options: [
    'Temel haklar, kişi hakları ve siyasi haklar Cumhurbaşkanlığı kararnamesiyle düzenlenebilir.',
    'Kanunda açıkça düzenlenen konularda Cumhurbaşkanlığı kararnamesi çıkarılamaz.',
    'Cumhurbaşkanlığı kararnameleri kanunlardan üstündür.',
    'TBMM onayı olmadan hiçbir konuda Cumhurbaşkanlığı kararnamesi çıkarılamaz.'
  ],
  correctIndex: 1,
  difficulty: 'zor',
  aciklama: 'Cumhurbaşkanlığı kararnamesi, yürütme yetkisine ilişkin konularda çıkarılabilir. Ancak kanunda açıkça düzenlenen konularda Cumhurbaşkanlığı kararnamesi çıkarılamaz. Ayrıca temel haklar, kişi hakları ve siyasi haklar bu yolla düzenlenemez.',
},
{
  id: 'v018',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre milletvekili seçilebilmek için en az kaç yaşını doldurmuş olmak gerekir?',
  options: [
    '18',
    '21',
    '25',
    '30'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: '2017 Anayasa değişikliğiyle milletvekili seçilme yaşı 25’ten 18’e indirilmiştir. Bu nedenle milletvekili seçilebilmek için en az 18 yaşını doldurmuş olmak gerekir.',
},
{
  id: 'v019',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre TBMM, Anayasa’da başka bir hüküm yoksa en az kaç milletvekili ile toplanır?',
  options: [
    '151',
    '184',
    '200',
    '301'
  ],
  correctIndex: 2,
  difficulty: 'orta',
  aciklama: 'TBMM üye tamsayısının en az üçte biri ile toplanır. TBMM 600 milletvekilinden oluştuğu için toplantı yeter sayısı 200’dür. Karar yeter sayısı ise hiçbir durumda üye tamsayısının dörtte birinin bir fazlasından az olamaz; bu sayı 151’dir.',
},
{
  id: 'v020',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre Anayasa değişikliği teklifinin TBMM üye tamsayısının en az kaçta biri tarafından yazılı olarak yapılması gerekir?',
  options: [
    'Üçte biri',
    'Beşte biri',
    'Dörtte biri',
    'Salt çoğunluğu'
  ],
  correctIndex: 0,
  difficulty: 'zor',
  aciklama: '1982 Anayasası’na göre Anayasa değişikliği teklifi, TBMM üye tamsayısının en az üçte biri tarafından yazılı olarak yapılabilir. TBMM 600 üyeden oluştuğu için bu sayı en az 200 milletvekilidir.',
},
{
  id: 'v021',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre olağanüstü hâl ilan etme yetkisi aşağıdakilerden hangisine aittir?',
  options: [
    'Türkiye Büyük Millet Meclisine',
    'Cumhurbaşkanına',
    'Anayasa Mahkemesine',
    'Hâkimler ve Savcılar Kuruluna'
  ],
  correctIndex: 1,
  difficulty: 'orta',
  aciklama: '1982 Anayasası’na göre olağanüstü hâl ilan etme yetkisi Cumhurbaşkanına aittir. Ancak bu karar aynı gün Resmî Gazete’de yayımlanır ve TBMM’nin onayına sunulur.',
},
{
  id: 'v022',
  category: 'vatandaslik',
  question: '1982 Anayasası’na göre Anayasa Mahkemesi üyeleri kaç kişiden oluşur?',
  options: [
    '11',
    '13',
    '15',
    '17'
  ],
  correctIndex: 2,
  difficulty: 'orta',
  aciklama: '1982 Anayasası’na göre Anayasa Mahkemesi 15 üyeden oluşur. Üyelerin bir kısmı Cumhurbaşkanı, bir kısmı ise TBMM tarafından seçilir.',
},
//GENEL KÜLTÜR
{
  id: 'g001',
  category: 'guncel',
  question: '2025 Nobel Barış Ödülü aşağıdaki isimlerden hangisine verilmiştir?',
  options: [
    'Maria Corina Machado',
    'Narges Mohammadi',
    'Dmitry Muratov',
    'Abiy Ahmed Ali'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: '2025 Nobel Barış Ödülü, Venezuela’da demokratik haklar için yürüttüğü çalışmalar nedeniyle Maria Corina Machado’ya verilmiştir.',
},
{
  id: 'g002',
  category: 'guncel',
  question: '2025 yılında UNESCO Dünya Miras Listesi’ne Türkiye’den eklenen kültürel miras alanı aşağıdakilerden hangisidir?',
  options: [
    'Sardes Antik Kenti ve Bin Tepe Lidya Tümülüsleri',
    'Göbeklitepe',
    'Arslantepe Höyüğü',
    'Gordion'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Sardes Antik Kenti ve Bin Tepe Lidya Tümülüsleri, 2025 yılında UNESCO Dünya Miras Listesi’ne kaydedilmiştir. Göbeklitepe 2018’de, Arslantepe Höyüğü 2021’de, Gordion ise 2023’te listeye alınmıştır.',
},
{
  id: 'g003',
  category: 'guncel',
  question: '2025 Nobel Edebiyat Ödülü aşağıdaki yazarlardan hangisine verilmiştir?',
  options: [
    'László Krasznahorkai',
    'Jon Fosse',
    'Annie Ernaux',
    'Abdulrazak Gurnah'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: '2025 Nobel Edebiyat Ödülü, Macar yazar László Krasznahorkai’ye verilmiştir. Jon Fosse 2023, Annie Ernaux 2022, Abdulrazak Gurnah ise 2021 Nobel Edebiyat Ödülü sahibidir.',
},
{
  id: 'g004',
  category: 'guncel',
  question: '2025 Nobel Kimya Ödülü aşağıdaki çalışmalardan hangisi nedeniyle verilmiştir?',
  options: [
    'Metal-organik kafeslerin geliştirilmesi',
    'mRNA aşı teknolojisinin geliştirilmesi',
    'Kuantum noktalarının keşfi ve sentezi',
    'Protein yapılarının hesaplamalı olarak tahmin edilmesi'
  ],
  correctIndex: 0,
  difficulty: 'zor',
  aciklama: '2025 Nobel Kimya Ödülü, Susumu Kitagawa, Richard Robson ve Omar M. Yaghi’ye metal-organik kafeslerin geliştirilmesi çalışmaları nedeniyle verilmiştir. Bu yapılar gaz depolama, su toplama ve çevresel arıtma gibi alanlarda kullanılabilmektedir.',
},
{
  id: 'g005',
  category: 'guncel',
  question: '2025 Nobel Fizik Ödülü aşağıdaki çalışmalardan hangisi nedeniyle verilmiştir?',
  options: [
    'Elektrik devresinde makroskobik kuantum tünelleme ve enerji kuantizasyonunun keşfi',
    'Kuantum noktalarının keşfi ve sentezi',
    'Kara deliklerin evrimsel yapısının açıklanması',
    'Grafenin iki boyutlu yapısının deneysel olarak elde edilmesi'
  ],
  correctIndex: 0,
  difficulty: 'zor',
  aciklama: '2025 Nobel Fizik Ödülü, John Clarke, Michel H. Devoret ve John M. Martinis’e elektrik devresinde makroskobik kuantum mekaniksel tünelleme ve enerji kuantizasyonu keşifleri nedeniyle verilmiştir.',
},
{
  id: 'g006',
  category: 'guncel',
  question: '2025 Nobel Fizyoloji veya Tıp Ödülü aşağıdaki çalışmalardan hangisi nedeniyle verilmiştir?',
  options: [
    'Periferik bağışıklık toleransı konusundaki keşifler',
    'mRNA aşı teknolojisinin geliştirilmesi',
    'Hepatit C virüsünün keşfi',
    'İnsan genom diziliminin tamamlanması'
  ],
  correctIndex: 0,
  difficulty: 'zor',
  aciklama: '2025 Nobel Fizyoloji veya Tıp Ödülü, Mary E. Brunkow, Frederick J. Ramsdell ve Shimon Sakaguchi’ye periferik bağışıklık toleransı konusundaki keşifleri nedeniyle verilmiştir. Bu çalışmalar, bağışıklık sisteminin vücudun kendi dokularına saldırmasını engelleyen mekanizmaların anlaşılmasını sağlamıştır.',
},
{
  id: 'g007',
  category: 'guncel',
  question: '2025 Nobel Ekonomi Ödülü aşağıdaki isimlerden hangilerine verilmiştir?',
  options: [
    'Joel Mokyr, Philippe Aghion ve Peter Howitt',
    'Daron Acemoğlu, Simon Johnson ve James A. Robinson',
    'Ben Bernanke, Douglas Diamond ve Philip Dybvig',
    'Paul Milgrom ve Robert Wilson'
  ],
  correctIndex: 0,
  difficulty: 'zor',
  aciklama: '2025 Nobel Ekonomi Ödülü, yenilik odaklı ekonomik büyümeyi açıklayan çalışmaları nedeniyle Joel Mokyr, Philippe Aghion ve Peter Howitt’e verilmiştir. Daron Acemoğlu, Simon Johnson ve James A. Robinson 2024 Nobel Ekonomi Ödülü’nü almıştır.',
},
{
  id: 'g008',
  category: 'guncel',
  question: '2025 yılı itibarıyla UNESCO Dünya Miras Listesi’nde Türkiye’den kayıtlı miras alanı sayısı kaç olmuştur?',
  options: [
    '20',
    '21',
    '22',
    '23'
  ],
  correctIndex: 2,
  difficulty: 'orta',
  aciklama: 'Sardes Antik Kenti ve Bin Tepe Lidya Tümülüsleri’nin 2025 yılında listeye alınmasıyla UNESCO Dünya Miras Listesi’nde Türkiye’den kayıtlı miras alanı sayısı 22’ye yükselmiştir.',
},
{
  id: 'g009',
  category: 'guncel',
  question: 'Expo 2025 Dünya Fuarı aşağıdaki şehirlerden hangisinde düzenlenmiştir?',
  options: [
    'Osaka',
    'Dubai',
    'Paris',
    'Roma'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Expo 2025 Dünya Fuarı, Japonya’nın Osaka kentinde düzenlenmiştir. Fuarın teması “Designing Future Society for Our Lives” olarak belirlenmiştir.'
},
{
  id: 'g010',
  category: 'guncel',
  question: 'Birleşmiş Milletler tarafından 2025 yılı hangi tema ile ilan edilmiştir?',
  options: [
    'Uluslararası Kooperatifler Yılı',
    'Uluslararası Barış ve Güvenlik Yılı',
    'Uluslararası Su Verimliliği Yılı',
    'Uluslararası Biyoçeşitlilik Yılı'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Birleşmiş Milletler Genel Kurulu, 2025 yılını “Uluslararası Kooperatifler Yılı” ilan etmiştir. Teması “Kooperatifler Daha İyi Bir Dünya Kurar” olarak belirlenmiştir.',
},
{
  id: 'g011',
  category: 'guncel',
  question: '2025 Avrupa Kültür Başkentleri aşağıdakilerden hangileridir?',
  options: [
    'Chemnitz ve Nova Gorica',
    'Oulu ve Trenčín',
    'Tartu ve Bad Ischl',
    'Elefsina ve Timișoara'
  ],
  correctIndex: 0,
  difficulty: 'zor',
  aciklama: '2025 Avrupa Kültür Başkentleri Almanya’dan Chemnitz ve Slovenya’dan Nova Gorica’dır. Nova Gorica, İtalya’daki Gorizia ile sınır ötesi ortak kültür programı yürütmüştür.'
},
{
  id: 'g012',
  category: 'guncel',
  question: '2025 Dünya Oyunları aşağıdaki şehirlerden hangisinde düzenlenmiştir?',
  options: [
    'Chengdu',
    'Tokyo',
    'Seul',
    'Bangkok'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: '2025 Dünya Oyunları, Çin’in Chengdu kentinde düzenlenmiştir. Dünya Oyunları, olimpik programda yer almayan veya olimpiyatlarda sınırlı yer alan spor dallarını içeren çok sporlu bir organizasyondur.'
},
{
  id: 'g013',
  category: 'guncel',
  question: '2025 İslami Dayanışma Oyunları aşağıdaki şehirlerden hangisinde düzenlenmiştir?',
  options: [
    'Riyad',
    'Konya',
    'Doha',
    'Bakü'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: '2025 İslami Dayanışma Oyunları, Suudi Arabistan’ın başkenti Riyad’da düzenlenmiştir. Organizasyonun 6. edisyonu 7-21 Kasım 2025 tarihleri arasında yapılmıştır.'
},
{
  id: 'g014',
  category: 'guncel',
  question: '2025 Dünya Atletizm Şampiyonası aşağıdaki şehirlerden hangisinde düzenlenmiştir?',
  options: [
    'Tokyo',
    'Budapeşte',
    'Pekin',
    'Doha'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: '2025 Dünya Atletizm Şampiyonası, Japonya’nın Tokyo kentinde 13-21 Eylül 2025 tarihleri arasında düzenlenmiştir.'
},
{
  id: 'g015',
  category: 'guncel',
  question: '2026 Kış Olimpiyatları aşağıdaki yerlerden hangisinde düzenlenmiştir?',
  options: [
    'Milano-Cortina',
    'Pekin',
    'PyeongChang',
    'Soçi'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: '2026 Kış Olimpiyatları, İtalya’nın Milano ve Cortina d’Ampezzo merkezli ev sahipliğinde düzenlenmiştir. Oyunlar 6-22 Şubat 2026 tarihleri arasında yapılmıştır.'
},
{
  id: 'g016',
  category: 'guncel',
  question: '2025 Akademi Ödülleri’nde “En İyi Film” ödülünü kazanan yapım aşağıdakilerden hangisidir?',
  options: [
    'Anora',
    'The Brutalist',
    'Conclave',
    'Dune: Part Two'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: '2025 Akademi Ödülleri’nde En İyi Film ödülünü Anora kazanmıştır. Film ayrıca yönetmen, özgün senaryo ve kurgu gibi önemli dallarda da ödül almıştır.',
},
{
  id: 'g017',
  category: 'guncel',
  question: '“Suç ve Ceza” adlı romanın başkahramanı aşağıdakilerden hangisidir?',
  options: [
    'Raskolnikov',
    'Prens Mışkin',
    'Jean Valjean',
    'Gregor Samsa'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Suç ve Ceza, Fyodor Dostoyevski’nin en bilinen romanlarından biridir. Romanın başkahramanı Rodion Romanoviç Raskolnikov’dur. Prens Mışkin, Dostoyevski’nin Budala romanının; Jean Valjean, Victor Hugo’nun Sefiller romanının; Gregor Samsa ise Kafka’nın Dönüşüm adlı eserinin karakteridir.',
},
{
  id: 'g018',
  category: 'guncel',
  question: '“Guernica” adlı ünlü tablo aşağıdaki ressamlardan hangisine aittir?',
  options: [
    'Pablo Picasso',
    'Salvador Dalí',
    'Vincent van Gogh',
    'Claude Monet'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Guernica, Pablo Picasso’nun en bilinen eserlerinden biridir. Tablo, İspanya İç Savaşı sırasında Guernica kentinin bombalanmasını konu alır ve savaş karşıtı güçlü bir sembol olarak kabul edilir.',
},
{
  id: 'g019',
  category: 'guncel',
  question: '“1984” adlı distopik romanda her şeyi gözetleyen totaliter otoriteyi temsil eden ifade aşağıdakilerden hangisidir?',
  options: [
    'Büyük Birader',
    'Kaptan Nemo',
    'Don Kişot',
    'Dr. Jekyll'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'George Orwell’in 1984 adlı romanında “Büyük Birader”, toplumun sürekli gözetim altında tutulmasını ve totaliter devlet otoritesini temsil eder. Kaptan Nemo, Jules Verne’in; Don Kişot, Cervantes’in; Dr. Jekyll ise Robert Louis Stevenson’ın karakteridir.',
},
{
  id: 'g020',
  category: 'guncel',
  question: '“Yüzüklerin Efendisi” serisinde “Tek Yüzük”ü yok etmek için Mordor’a götüren karakter aşağıdakilerden hangisidir?',
  options: [
    'Frodo Baggins',
    'Aragorn',
    'Gandalf',
    'Legolas'
  ],
  correctIndex: 0,
  difficulty: 'kolay',
  aciklama: 'J. R. R. Tolkien’in Yüzüklerin Efendisi serisinde Tek Yüzük’ü yok etmek üzere Mordor’a götürme görevini Frodo Baggins üstlenir. Samwise Gamgee bu yolculukta ona eşlik eden en önemli karakterlerden biridir.',
},
{
  id: 'g021',
  category: 'guncel',
  question: '“Sefiller” adlı romanın yazarı aşağıdakilerden hangisidir?',
  options: [
    'Victor Hugo',
    'Lev Tolstoy',
    'Charles Dickens',
    'Fyodor Dostoyevski'
  ],
  correctIndex: 0,
  difficulty: 'kolay',
  aciklama: 'Sefiller, Fransız yazar Victor Hugo’nun en önemli eserlerinden biridir. Romanın en bilinen karakterlerinden biri Jean Valjean’dır.',
},
{
  id: 'g022',
  category: 'guncel',
  question: '“İnci Küpeli Kız” adlı ünlü tablo aşağıdaki ressamlardan hangisine aittir?',
  options: [
    'Johannes Vermeer',
    'Rembrandt',
    'Leonardo da Vinci',
    'Michelangelo'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'İnci Küpeli Kız, Hollandalı ressam Johannes Vermeer’in en bilinen eserlerinden biridir. Tablo, ışık kullanımı ve figürün etkileyici bakışıyla sanat tarihinde önemli bir yere sahiptir.',
},
{
  id: 'g023',
  category: 'guncel',
  question: '“Don Kişot” adlı eserde Don Kişot’un sadık yardımcısı aşağıdakilerden hangisidir?',
  options: [
    'Sancho Panza',
    'Dorian Gray',
    'Robinson Crusoe',
    'Monte Cristo'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Miguel de Cervantes’in Don Kişot adlı eserinde Don Kişot’un sadık yardımcısı Sancho Panza’dır. Dorian Gray, Oscar Wilde’ın; Robinson Crusoe, Daniel Defoe’nun; Monte Cristo ise Alexandre Dumas’nın eserlerindeki karakterlerle ilişkilidir.',
},
{
  id: 'g024',
  category: 'guncel',
  question: '“Kaplumbağa Terbiyecisi” adlı ünlü tablo aşağıdaki sanatçılardan hangisine aittir?',
  options: [
    'Osman Hamdi Bey',
    'Şeker Ahmet Paşa',
    'İbrahim Çallı',
    'Fikret Mualla'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Kaplumbağa Terbiyecisi, Osman Hamdi Bey’in en bilinen eserlerinden biridir. Osmanlı resim sanatının sembol eserleri arasında kabul edilir.',
},
{
  id: 'g025',
  category: 'guncel',
  question: 'İran ile ABD arasındaki gerilimlerde sıkça gündeme gelen Hürmüz Boğazı, aşağıdaki su yollarından hangilerini birbirine bağlar?',
  options: [
    'Basra Körfezi ile Umman Körfezi',
    'Kızıldeniz ile Aden Körfezi',
    'Akdeniz ile Kızıldeniz',
    'Karadeniz ile Marmara Denizi'
  ],
  correctIndex: 0,
  difficulty: 'orta',
  aciklama: 'Hürmüz Boğazı, İran ile Umman arasında yer alan stratejik bir su yoludur. Basra Körfezi’ni Umman Körfezi ve dolayısıyla Arap Denizi’ne bağlar. Petrol ve doğal gaz taşımacılığı açısından dünyanın en kritik geçiş noktalarından biridir.',
}
];
