export interface Question {
  id: string;
  category: 'tarih' | 'cografya' | 'vatandaslik';
  question: string;
  options: string[];
  correctIndex: number;
  difficulty: 'kolay' | 'orta' | 'zor';
  aciklama?: string;
}

export const QUESTION_POOL: Question[] = [
  // TARİH
  {
    id: 'h001',
    category: 'tarih',
    question: 'Türkiye Büyük Millet Meclisi hangi tarihte açılmıştır?',
    options: ['23 Nisan 1920', '29 Ekim 1923', '30 Ağustos 1922', '1 Kasım 1922'],
    correctIndex: 0,
    difficulty: 'kolay',
    aciklama: 'TBMM, 23 Nisan 1920\'de Ankara\'da açıldı ve millî egemenliğe dayalı yeni Türk devletinin temeli atıldı. Bu tarih bugün Ulusal Egemenlik ve Çocuk Bayramı olarak kutlanır.',
  },
  {
    id: 'h002',
    category: 'tarih',
    question: 'Lozan Antlaşması hangi yılda imzalanmıştır?',
    options: ['1920', '1921', '1923', '1925'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Lozan Barış Antlaşması 24 Temmuz 1923\'te imzalandı; yeni Türk devletinin bağımsızlığı uluslararası alanda tanındı ve kapitülasyonlar kaldırıldı.',
  },
  {
    id: 'h003',
    category: 'tarih',
    question: 'Kurtuluş Savaşı\'nda Sakarya Meydan Muharebesi hangi yılda yaşandı?',
    options: ['1919', '1920', '1921', '1922'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Sakarya Meydan Muharebesi 23 Ağustos-13 Eylül 1921\'de kazanıldı. 1683 Viyana bozgunundan beri süren geri çekilme sona erdi; bu zaferle Mustafa Kemal\'e "Gazi" unvanı ve mareşallik rütbesi verildi.',
  },
  {
    id: 'h004',
    category: 'tarih',
    question: 'Osmanlı Devleti\'nin kuruluş yılı hangisidir?',
    options: ['1071', '1176', '1299', '1453'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Osmanlı Devleti, Osman Bey önderliğinde 1299\'da Söğüt çevresinde kuruldu. Bir uç beyliğiyken zamanla üç kıtaya yayılan büyük bir imparatorluğa dönüştü.',
  },
  {
    id: 'h005',
    category: 'tarih',
    question: 'İstanbul\'un fethini gerçekleştiren Osmanlı padişahı kimdir?',
    options: ['I. Murat', 'II. Murat', 'II. Mehmet', 'I. Selim'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'İstanbul 29 Mayıs 1453\'te II. Mehmet (Fatih Sultan Mehmet) tarafından fethedildi. Bu olay Orta Çağ\'ın sonu, Yeni Çağ\'ın başlangıcı kabul edilir.',
  },
  {
    id: 'h006',
    category: 'tarih',
    question: 'Birinci Dünya Savaşı hangi olayla başlamıştır?',
    options: [
      'Almanya\'nın Fransa\'yı işgali',
      'Avusturya Veliahtı\'nın öldürülmesi',
      'Osmanlı\'nın savaşa girmesi',
      'Rusya\'nın seferberlik ilan etmesi',
    ],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'I. Dünya Savaşı, 28 Haziran 1914\'te Avusturya-Macaristan veliahtı Franz Ferdinand\'ın Saraybosna\'da bir Sırp milliyetçisi tarafından öldürülmesiyle başladı.',
  },
  {
    id: 'h007',
    category: 'tarih',
    question: 'Türkiye\'de çok partili siyasi hayat hangi yılda başlamıştır?',
    options: ['1923', '1930', '1946', '1950'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Türkiye\'de çok partili siyasi hayata geçiş 1946\'da gerçekleşti; Demokrat Parti kuruldu ve ilk kez birden fazla partinin katıldığı seçim yapıldı. 1950\'de DP iktidara geldi.',
  },
  {
    id: 'h008',
    category: 'tarih',
    question: 'Mondros Ateşkesi hangi tarihte imzalanmıştır?',
    options: ['30 Ekim 1918', '30 Kasım 1918', '11 Kasım 1918', '18 Ocak 1919'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Mondros Ateşkesi 30 Ekim 1918\'de imzalandı. Osmanlı I. Dünya Savaşı\'ndan çekildi; ağır hükümleriyle Anadolu\'nun işgaline zemin hazırladı.',
  },
  {
    id: 'h009',
    category: 'tarih',
    question: 'Türk alfabesi hangi yılda kabul edilmiştir?',
    options: ['1924', '1926', '1928', '1932'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Harf İnkılabı (Latin alfabesi) 1 Kasım 1928\'de kabul edildi; Arap alfabesi bırakılarak Türkçeye uygun Latin temelli yeni Türk alfabesine geçildi. Okuryazarlığı artırmak için Millet Mektepleri açıldı.',
  },
  {
    id: 'h010',
    category: 'tarih',
    question: 'Atatürk hangi tarihte vefat etmiştir?',
    options: ['10 Kasım 1938', '10 Kasım 1937', '19 Mayıs 1938', '29 Ekim 1938'],
    correctIndex: 0,
    difficulty: 'kolay',
    aciklama: 'Mustafa Kemal Atatürk 10 Kasım 1938\'de Dolmabahçe Sarayı\'nda vefat etti. Her yıl 10 Kasım\'da saat 09.05\'te anılır.',
  },
  {
    id: 'h011',
    category: 'tarih',
    question: 'Malazgirt Muharebesi hangi yılda gerçekleşmiştir?',
    options: ['1071', '1176', '1243', '1302'],
    correctIndex: 0,
    difficulty: 'kolay',
    aciklama: 'Malazgirt Meydan Muharebesi\'nde (26 Ağustos 1071) Sultan Alparslan, Bizans ordusunu yendi. Anadolu\'nun kapıları Türklere açıldı ve Anadolu\'nun Türkleşme süreci başladı.',
  },
  {
    id: 'h012',
    category: 'tarih',
    question: 'Misak-ı Millî hangi tarihte kabul edilmiştir?',
    options: ['Ocak 1920', 'Nisan 1920', 'Temmuz 1920', 'Ekim 1920'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Misak-ı Millî (Millî Ant), son Osmanlı Mebusan Meclisi tarafından 28 Ocak 1920\'de kabul edildi. Yeni Türk devletinin sınırlarını ve bağımsızlık ilkelerini belirleyen temel belgedir.',
  },
  {
    id: 'h013',
    category: 'tarih',
    question: 'Kurtuluş Savaşı\'nda Doğu Cephesi\'nde Ermenistan\'a karşı kazanılan zafer sonucunda imzalanan ve TBMM\'nin uluslararası alanda imzaladığı ilk antlaşma aşağıdakilerden hangisidir?',
    options: ['Gümrü Antlaşması', 'Moskova Antlaşması', 'Kars Antlaşması', 'Ankara Antlaşması'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Doğu Cephesi\'nde Kâzım Karabekir komutasında Ermenistan\'a karşı kazanılan başarının ardından 3 Aralık 1920\'de Gümrü Antlaşması imzalanmıştır. Bu, TBMM Hükûmeti\'nin imzaladığı ilk antlaşmadır. (Moskova ve Kars 1921, Ankara Antlaşması Fransa ile 1921\'dir.)',
  },
  {
    id: 'h014',
    category: 'tarih',
    question: 'Osmanlı Devleti\'nin Avrupa\'da ilk kez büyük çaplı toprak kaybettiği ve klasik dönemlendirmede "Gerileme Dönemi"nin başlangıcı olarak kabul edilen antlaşma aşağıdakilerden hangisidir?',
    options: ['Karlofça Antlaşması', 'Pasarofça Antlaşması', 'Küçük Kaynarca Antlaşması', 'Ziştovi Antlaşması'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '1699 Karlofça Antlaşması ile Osmanlı, Kutsal İttifak devletlerine (Avusturya, Venedik, Lehistan) Macaristan ve Mora gibi önemli topraklar bırakmış; ilk kez geniş çaplı toprak kaybetmiştir. Bu antlaşma Duraklama Dönemi\'nin sonu, Gerileme Dönemi\'nin başlangıcı sayılır.',
  },
  {
    id: 'h015',
    category: 'tarih',
    question: '"Türk" adını resmî devlet adı olarak kullanan ilk Türk devleti aşağıdakilerden hangisidir?',
    options: ['Asya Hun Devleti', 'Göktürk (Kök Türk) Devleti', 'Uygur Devleti', 'Avar Devleti'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: '"Türk" sözcüğünü ilk kez resmî devlet adı olarak Göktürkler (Kök Türkler) kullanmıştır. Ayrıca Türk adının geçtiği ilk yazılı Türkçe belgeler olan Orhun (Göktürk) Yazıtları da bu döneme aittir.',
  },
  {
    id: 'h016',
    category: 'tarih',
    question: 'Türkiye\'de kadınlara milletvekili seçme ve seçilme hakkı hangi yıl tanınmıştır?',
    options: ['1930', '1933', '1934', '1935'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Kadınlara siyasi haklar kademeli verilmiştir: 1930\'da belediye seçimlerine katılma, 1933\'te muhtar seçme-seçilme, 5 Aralık 1934\'te ise milletvekili seçme ve seçilme hakkı tanınmıştır. Türkiye, kadınlara bu hakkı pek çok Avrupa ülkesinden önce vermiştir.',
  },
  {
    id: 'h017',
    category: 'tarih',
    question: '751 Talas Savaşı\'nın Türk-İslam tarihi açısından en önemli sonucu aşağıdakilerden hangisidir?',
    options: [
      'Türklerin kitleler hâlinde İslamiyet\'i kabul etmeye başlaması',
      'Abbasi Devleti\'nin yıkılması',
      'Anadolu\'nun kapılarının Türklere açılması',
      'Emevi Devleti\'nin kurulması',
    ],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '751 Talas Savaşı\'nda Abbasiler ile Çinliler karşı karşıya geldi; Karluk Türklerinin Abbasileri desteklemesiyle savaşı Müslümanlar kazandı. Sonrasında Türk-Arap ilişkileri yumuşadı ve Türkler kitleler hâlinde İslamiyet\'i kabul etmeye başladı. "Anadolu\'nun kapılarının açılması" ise 1071 Malazgirt\'in sonucudur.',
  },
  {
    id: 'h018',
    category: 'tarih',
    question: 'Osmanlı Devleti\'nde Yeniçeri Ocağı hangi padişah döneminde kurulmuştur?',
    options: ['Orhan Bey', 'I. Murat (Hüdavendigâr)', 'Yıldırım Bayezid', 'I. Mehmet (Çelebi)'],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Yeniçeri Ocağı, devşirme sistemine dayalı olarak I. Murat (Hüdavendigâr) döneminde kurulmuştur. Sık karıştırılır: Osmanlı\'nın ilk düzenli ordusu olan "yaya ve müsellemler" ise Orhan Bey dönemindedir.',
  },
  {
    id: 'h019',
    category: 'tarih',
    question: 'Lozan Antlaşması\'nda çözüme kavuşturulamayıp sonraya bırakılan ve 1926\'da Türkiye aleyhine (İngiltere/Irak lehine) sonuçlanan sorun aşağıdakilerden hangisidir?',
    options: ['Musul Sorunu', 'Hatay Sorunu', 'Boğazlar Sorunu', 'Nüfus Mübadelesi'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Lozan\'da Musul sorunu çözülemedi ve İngiltere ile ikili görüşmeye bırakıldı. 1926 Ankara Antlaşması ile Musul, İngiliz mandasındaki Irak\'a bırakıldı. Boğazlar 1936 Montrö, Hatay 1939\'da çözüldü; nüfus mübadelesi ise Lozan\'da karara bağlandı.',
  },
  {
    id: 'h020',
    category: 'tarih',
    question: '3 Mart 1924\'te kabul edilen Tevhid-i Tedrisat (Öğretim Birliği) Kanunu\'nun temel amacı aşağıdakilerden hangisidir?',
    options: [
      'Tüm eğitim kurumlarını Millî Eğitim Bakanlığı çatısı altında toplamak',
      'Latin harflerine geçmek',
      'İlk Türk üniversitesini kurmak',
      'Kapitülasyonları kaldırmak',
    ],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Tevhid-i Tedrisat Kanunu (3 Mart 1924) ile ülkedeki bütün okullar Millî Eğitim Bakanlığı\'na bağlanmış, medreseler kapatılmış ve eğitimde birlik sağlanmıştır. Laik ve millî eğitimin temelini atan inkılaptır. Aynı gün halifelik de kaldırılmıştır.',
  },
  {
    id: 'h021',
    category: 'tarih',
    question: '1176 Miryokefalon (Myriokephalon) Savaşı\'nın Türk tarihi açısından en önemli sonucu aşağıdakilerden hangisidir?',
    options: [
      'Anadolu\'nun kesin olarak Türk yurdu olduğunun kanıtlanması',
      'Bizans\'ın İstanbul\'u kaybetmesi',
      'Haçlı Seferleri\'nin başlaması',
      'Anadolu Selçuklu Devleti\'nin kurulması',
    ],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '1176 Miryokefalon Savaşı\'nda Anadolu Selçuklu Sultanı II. Kılıç Arslan, Bizans İmparatoru Manuel\'i yendi. Bu zaferle Bizans\'ın Anadolu\'yu geri alma umudu bitti; Anadolu kesin olarak Türk yurdu kabul edildi. Sık vurgulanır: Malazgirt (1071) Anadolu\'nun kapılarını açtı, Miryokefalon (1176) bunu kesinleştirdi.',
  },
  {
    id: 'h022',
    category: 'tarih',
    question: 'Türkiye\'nin Boğazlar üzerindeki egemenlik haklarını yeniden tam olarak kazanmasını sağlayan ve günümüzde hâlâ yürürlükte olan 1936 tarihli sözleşme aşağıdakilerden hangisidir?',
    options: ['Montrö Boğazlar Sözleşmesi', 'Lozan Boğazlar Sözleşmesi', 'Balkan Antantı', 'Sadabat Paktı'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '1936 Montrö Boğazlar Sözleşmesi ile Lozan\'da kurulan ve Boğazları kısıtlayan uluslararası komisyon kaldırıldı; Boğazların yönetimi ve askerî egemenliği tamamen Türkiye\'ye geçti. Sözleşme hâlâ yürürlüktedir. (Balkan Antantı 1934, Sadabat Paktı 1937 tarihli güvenlik antlaşmalarıdır.)',
  },
  {
    id: 'h023',
    category: 'tarih',
    question: 'Yeni Türk Devleti\'nin izleyeceği ekonomi politikalarının belirlendiği ve "Misak-ı İktisadî" (Ekonomi Andı) kararlarının alındığı kongre aşağıdakilerden hangisidir?',
    options: ['İzmir İktisat Kongresi', 'Sivas Kongresi', 'Erzurum Kongresi', 'Balıkesir Kongresi'],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: '1923 İzmir İktisat Kongresi\'nde milli ekonomiyi geliştirme kararları ("Misak-ı İktisadî") alındı; yerli üretim ve özel teşebbüs desteklendi. Lozan görüşmelerine ara verilen dönemde toplanmıştır. Sivas ve Erzurum, Kurtuluş Savaşı hazırlık dönemi kongreleridir.',
  },
  {
    id: 'h024',
    category: 'tarih',
    question: 'Kurtuluş Savaşı\'nın askerî safhasını sona erdiren ve 30 Ağustos 1922\'de Yunan ordusuna karşı kazanılan kesin zafer aşağıdakilerden hangisidir?',
    options: [
      'Başkomutanlık Meydan Muharebesi (Büyük Taarruz)',
      'I. İnönü Muharebesi',
      'Sakarya Meydan Muharebesi',
      'Kütahya-Eskişehir Muharebeleri',
    ],
    correctIndex: 0,
    difficulty: 'kolay',
    aciklama: '30 Ağustos 1922 Başkomutanlık Meydan Muharebesi (Büyük Taarruz) ile Yunan ordusu kesin yenilgiye uğratıldı ve savaşın askerî safhası sona erdi. Ardından Mudanya Ateşkesi (11 Ekim 1922) imzalandı. 30 Ağustos bugün Zafer Bayramı olarak kutlanır.',
  },
  // COĞRAFYA
  {
    id: 'c001',
    category: 'cografya',
    question: 'Türkiye\'nin en uzun nehri hangisidir?',
    options: ['Fırat', 'Dicle', 'Kızılırmak', 'Sakarya'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Kızılırmak (~1355 km), tamamen Türkiye sınırları içinde akan en uzun nehirdir; Sivas yakınlarından doğup Karadeniz\'e dökülür.',
  },
  {
    id: 'c002',
    category: 'cografya',
    question: 'Türkiye\'nin en yüksek dağı hangisidir?',
    options: ['Erciyes', 'Ağrı', 'Kaçkar', 'Uludağ'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'Ağrı Dağı 5137 m ile Türkiye\'nin en yüksek dağıdır; Doğu Anadolu\'da yer alan volkanik kökenli bir dağdır.',
  },
  {
    id: 'c003',
    category: 'cografya',
    question: 'Türkiye kaç komşu ülkeyle sınır paylaşmaktadır?',
    options: ['6', '7', '8', '9'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Türkiye\'nin 8 komşusu vardır: Yunanistan, Bulgaristan, Gürcistan, Ermenistan, Azerbaycan (Nahçıvan), İran, Irak ve Suriye.',
  },
  {
    id: 'c004',
    category: 'cografya',
    question: 'Marmara Denizi hangi iki denizi birbirine bağlar?',
    options: [
      'Karadeniz – Akdeniz',
      'Karadeniz – Ege Denizi',
      'Ege Denizi – Akdeniz',
      'Karadeniz – Kızıldeniz',
    ],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'Marmara Denizi, İstanbul ve Çanakkale boğazları aracılığıyla Karadeniz ile Ege Denizi\'ni birbirine bağlar.',
  },
  {
    id: 'c005',
    category: 'cografya',
    question: 'Türkiye\'nin en büyük gölü hangisidir?',
    options: ['Eğirdir Gölü', 'Van Gölü', 'Tuz Gölü', 'Beyşehir Gölü'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'Van Gölü (~3713 km²), Türkiye\'nin en büyük gölüdür; sodalı (acı) suyuyla bilinir ve Doğu Anadolu\'da yer alır.',
  },
  {
    id: 'c006',
    category: 'cografya',
    question: 'Karadeniz ikliminin en belirgin özelliği hangisidir?',
    options: [
      'Az yağışlı ve sıcak yazlar',
      'Her mevsim yağışlı',
      'Kışlar ılık, yazlar serin',
      'Kurak yazlar, bol yağışlı kışlar',
    ],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Karadeniz ikliminin en belirgin özelliği her mevsim yağış almasıdır; bu nedenle bölge gür ormanlarla kaplıdır.',
  },
  {
    id: 'c007',
    category: 'cografya',
    question: 'Türkiye hangi yarımkürededir?',
    options: [
      'Kuzey ve Doğu yarımküre',
      'Güney ve Doğu yarımküre',
      'Kuzey ve Batı yarımküre',
      'Güney ve Batı yarımküre',
    ],
    correctIndex: 0,
    difficulty: 'orta',
    aciklama: 'Türkiye, Ekvator\'un kuzeyinde (Kuzey yarımküre) ve Greenwich meridyeninin doğusunda (Doğu yarımküre) yer alır.',
  },
  {
    id: 'c008',
    category: 'cografya',
    question: 'Boğaziçi Köprüsü hangi şehirde yer almaktadır?',
    options: ['Ankara', 'İzmir', 'İstanbul', 'Bursa'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Boğaziçi (15 Temmuz Şehitler) Köprüsü İstanbul\'dadır ve Asya ile Avrupa yakalarını birbirine bağlar.',
  },
  {
    id: 'c009',
    category: 'cografya',
    question: 'Türkiye\'nin başkenti neresidir?',
    options: ['İstanbul', 'İzmir', 'Bursa', 'Ankara'],
    correctIndex: 3,
    difficulty: 'kolay',
    aciklama: 'Türkiye\'nin başkenti Ankara\'dır; 13 Ekim 1923\'te başkent ilan edilmiştir.',
  },
  {
    id: 'c010',
    category: 'cografya',
    question: 'Fırat ve Dicle nehirleri hangi denize dökülür?',
    options: ['Karadeniz', 'Hazar Denizi', 'Pers Körfezi', 'Kızıldeniz'],
    correctIndex: 2,
    difficulty: 'orta',
    aciklama: 'Fırat ve Dicle nehirleri Şattülarap\'ta birleşerek Basra (Pers) Körfezi\'ne dökülür.',
  },
  {
    id: 'c011',
    category: 'cografya',
    question: 'Türkiye\'nin yüzölçümü yaklaşık kaç km²\'dir?',
    options: ['580.000', '680.000', '780.000', '880.000'],
    correctIndex: 2,
    difficulty: 'zor',
    aciklama: 'Türkiye\'nin yüzölçümü yaklaşık 780.000 km²\'dir (göller dahil ~783.562 km²).',
  },
  {
    id: 'c012',
    category: 'cografya',
    question: 'Anadolu yarımadasını Avrupa\'dan ayıran boğaz hangisidir?',
    options: ['Çanakkale Boğazı', 'İstanbul Boğazı', 'Hürmüz Boğazı', 'Kıbrıs Boğazı'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'İstanbul Boğazı, Anadolu (Asya) yakasını Avrupa (Trakya) yakasından ayırır ve Karadeniz\'i Marmara Denizi\'ne bağlar.',
  },
  // VATANDAŞLIK
  {
    id: 'v001',
    category: 'vatandaslik',
    question: 'Türkiye Cumhuriyeti Anayasası kaçıncı maddede devletin niteliklerini belirtir?',
    options: ['1. Madde', '2. Madde', '3. Madde', '4. Madde'],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Anayasa\'nın 2. maddesi devletin niteliklerini sayar: demokratik, laik, sosyal bir hukuk devleti. (1. madde yönetim şeklinin Cumhuriyet olduğunu belirtir.)',
  },
  {
    id: 'v002',
    category: 'vatandaslik',
    question: 'TBMM kaç üyeden oluşmaktadır?',
    options: ['450', '500', '550', '600'],
    correctIndex: 3,
    difficulty: 'orta',
    aciklama: '2017 Anayasa değişikliğiyle TBMM\'nin milletvekili sayısı 550\'den 600\'e çıkarılmıştır.',
  },
  {
    id: 'v003',
    category: 'vatandaslik',
    question: 'Türkiye\'de oy kullanma yaşı kaçtır?',
    options: ['16', '17', '18', '21'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Türkiye\'de seçme (oy kullanma) yaşı 18\'dir.',
  },
  {
    id: 'v004',
    category: 'vatandaslik',
    question: 'Cumhurbaşkanlığı görevi kaç yıllık dönemler için geçerlidir?',
    options: ['4 yıl', '5 yıl', '6 yıl', '7 yıl'],
    correctIndex: 1,
    difficulty: 'kolay',
    aciklama: 'Cumhurbaşkanı 5 yıllık dönemler için seçilir ve en fazla iki dönem görev yapabilir.',
  },
  {
    id: 'v005',
    category: 'vatandaslik',
    question: 'Anayasa Mahkemesi\'nin görevi nedir?',
    options: [
      'Vergi uyuşmazlıklarını çözmek',
      'Kanunların anayasaya uygunluğunu denetlemek',
      'Milletvekili seçimlerini yönetmek',
      'İdari davaları karara bağlamak',
    ],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Anayasa Mahkemesi\'nin temel görevi, kanunların ve bazı düzenlemelerin Anayasa\'ya uygunluğunu denetlemektir.',
  },
  {
    id: 'v006',
    category: 'vatandaslik',
    question: 'Türkiye\'nin mevcut anayasası hangi yılda yürürlüğe girmiştir?',
    options: ['1961', '1971', '1980', '1982'],
    correctIndex: 3,
    difficulty: 'kolay',
    aciklama: 'Türkiye\'nin yürürlükteki anayasası 1982 Anayasası\'dır; 7 Kasım 1982\'de halkoyuyla kabul edilmiştir.',
  },
  {
    id: 'v007',
    category: 'vatandaslik',
    question: 'Türkiye\'de hangi mahkeme idari davaları çözer?',
    options: ['Yargıtay', 'Danıştay', 'Anayasa Mahkemesi', 'Sayıştay'],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'İdari davalara bakan yüksek mahkeme Danıştay\'dır. Yargıtay ise adli (hukuk ve ceza) davalara bakar.',
  },
  {
    id: 'v008',
    category: 'vatandaslik',
    question: 'Türkiye Büyük Millet Meclisi\'nin olağan toplantı dönemi ne zamandır?',
    options: ['Ocak-Haziran', 'Ekim-Temmuz', 'Mart-Ekim', 'Nisan-Eylül'],
    correctIndex: 1,
    difficulty: 'zor',
    aciklama: 'TBMM, Anayasa gereği her yıl Ekim ayının ilk günü kendiliğinden toplanır ve genellikle Temmuz başında tatile girer.',
  },
  {
    id: 'v009',
    category: 'vatandaslik',
    question: 'Türkiye\'de devletin resmi dili nedir?',
    options: ['Kürtçe', 'Arapça', 'Türkçe', 'Osmanlıca'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Anayasa\'ya göre Türkiye Cumhuriyeti\'nin resmî dili Türkçedir.',
  },
  {
    id: 'v010',
    category: 'vatandaslik',
    question: 'Cumhurbaşkanı en fazla kaç dönem görev yapabilir?',
    options: ['1 dönem', '2 dönem', '3 dönem', 'Sınır yok'],
    correctIndex: 1,
    difficulty: 'orta',
    aciklama: 'Cumhurbaşkanı en fazla iki dönem (her biri 5 yıl) görev yapabilir.',
  },
  {
    id: 'v011',
    category: 'vatandaslik',
    question: 'Türkiye\'de hangi organ kanun yapma yetkisine sahiptir?',
    options: ['Cumhurbaşkanlığı', 'Bakanlar Kurulu', 'TBMM', 'Danıştay'],
    correctIndex: 2,
    difficulty: 'kolay',
    aciklama: 'Yasama yetkisi, yani kanun yapma yetkisi, Türk Milleti adına Türkiye Büyük Millet Meclisi\'ne aittir ve devredilemez.',
  },
  {
    id: 'v012',
    category: 'vatandaslik',
    question: 'Türkiye hangi yılda BM\'ye üye olmuştur?',
    options: ['1945', '1946', '1948', '1952'],
    correctIndex: 0,
    difficulty: 'zor',
    aciklama: 'Türkiye, Birleşmiş Milletler\'in kurucu üyelerindendir ve 1945\'te BM\'ye üye olmuştur.',
  },
];
